/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

    import com.sximi.mragent.*;
    import com.sximi.mragent.ImiBodySkeleton;

public class DataUtil {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DataUtil(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DataUtil obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DataUtil obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_javaJNI.delete_DataUtil(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static ImiBodySkeleton createImiBodySkeleton() {
    return new ImiBodySkeleton(mragent_javaJNI.DataUtil_createImiBodySkeleton(), true);
  }

  public DataUtil() {
    this(mragent_javaJNI.new_DataUtil(), true);
  }

}
