/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

    import com.sximi.mragent.*;
    import com.sximi.mragent.ImiBodySkeleton;

public class IFloatProperty extends IImiDeviceProperty {
  private transient long swigCPtr;

  public IFloatProperty(long cPtr, boolean cMemoryOwn) {
    super(mragent_javaJNI.IFloatProperty_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(IFloatProperty obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(IFloatProperty obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_javaJNI.delete_IFloatProperty(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IFloatProperty() {
    this(mragent_javaJNI.new_IFloatProperty__SWIG_0(), true);
  }

  public IFloatProperty(float v) {
    this(mragent_javaJNI.new_IFloatProperty__SWIG_1(v), true);
  }

  public void set(float val) {
    mragent_javaJNI.IFloatProperty_set(swigCPtr, this, val);
  }

  public float get() {
    return mragent_javaJNI.IFloatProperty_get(swigCPtr, this);
  }

  public int dataSize() {
    return mragent_javaJNI.IFloatProperty_dataSize(swigCPtr, this);
  }

}
