/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

    import com.sximi.mragent.*;
    import com.sximi.mragent.ImiBodySkeleton;

public class IImiActionFrame extends IImiBaseFrame {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IImiActionFrame(long cPtr, boolean cMemoryOwn) {
    super(mragent_javaJNI.IImiActionFrame_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IImiActionFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        mragent_javaJNI.delete_IImiActionFrame(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IImiActionFrame() {
    this(mragent_javaJNI.new_IImiActionFrame(), true);
  }

  public static IImiActionFrame asMe(IImiBaseFrame p) {
    long cPtr = mragent_javaJNI.IImiActionFrame_asMe(IImiBaseFrame.getCPtr(p), p);
    return (cPtr == 0) ? null : new IImiActionFrame(cPtr, true);
  }

  public IImiUserTrackFrame getAccompanyFrame() {
    long cPtr = mragent_javaJNI.IImiActionFrame_getAccompanyFrame(swigCPtr, this);
    return (cPtr == 0) ? null : new IImiUserTrackFrame(cPtr, true);
  }

  public String getActionsData() {
    return mragent_javaJNI.IImiActionFrame_getActionsData(swigCPtr, this);
  }

}
