/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

    import com.sximi.mragent.*;
    import com.sximi.mragent.ImiBodySkeleton;

public class IImiBaseDevice {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected IImiBaseDevice(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IImiBaseDevice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_javaJNI.delete_IImiBaseDevice(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean sendCommand(SWIGTYPE_p_cmd_data_native cmd) {
    return mragent_javaJNI.IImiBaseDevice_sendCommand(swigCPtr, this, SWIGTYPE_p_cmd_data_native.getCPtr(cmd));
  }

  public void setOnExceptionHandler(MrAgentExceptionHandler exceptionHandler) {
    mragent_javaJNI.IImiBaseDevice_setOnExceptionHandler(swigCPtr, this, MrAgentExceptionHandler.getCPtr(exceptionHandler), exceptionHandler);
  }

  public int getMrManagerStatus() {
    return mragent_javaJNI.IImiBaseDevice_getMrManagerStatus(swigCPtr, this);
  }

  public IImiBaseSensor getSensor(int sensorType) {
    long cPtr = mragent_javaJNI.IImiBaseDevice_getSensor(swigCPtr, this, sensorType);
    return (cPtr == 0) ? null : new IImiBaseSensor(cPtr, true);
  }

  public int open(int openFlag) {
    return mragent_javaJNI.IImiBaseDevice_open(swigCPtr, this, openFlag);
  }

  public int close() {
    return mragent_javaJNI.IImiBaseDevice_close(swigCPtr, this);
  }

  public ImiVersions getVersions() {
    return new ImiVersions(mragent_javaJNI.IImiBaseDevice_getVersions(swigCPtr, this), true);
  }

  public int setProperty(int propId, IImiDeviceProperty prop) {
    return mragent_javaJNI.IImiBaseDevice_setProperty(swigCPtr, this, propId, IImiDeviceProperty.getCPtr(prop), prop);
  }

  public int getProperty(int propId, IImiDeviceProperty prop) {
    return mragent_javaJNI.IImiBaseDevice_getProperty(swigCPtr, this, propId, IImiDeviceProperty.getCPtr(prop), prop);
  }

}
