/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

    import com.sximi.mragent.*;
    import com.sximi.mragent.ImiBodySkeleton;

public class IImiBaseFrame {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected IImiBaseFrame(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IImiBaseFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_javaJNI.delete_IImiBaseFrame(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getSensorType() {
    return mragent_javaJNI.IImiBaseFrame_getSensorType(swigCPtr, this);
  }

  public int getFrameNum() {
    return mragent_javaJNI.IImiBaseFrame_getFrameNum(swigCPtr, this);
  }

  public int getTimeStamp() {
    return mragent_javaJNI.IImiBaseFrame_getTimeStamp(swigCPtr, this);
  }

  public int getWidth() {
    return mragent_javaJNI.IImiBaseFrame_getWidth(swigCPtr, this);
  }

  public int getHeight() {
    return mragent_javaJNI.IImiBaseFrame_getHeight(swigCPtr, this);
  }

  public int getDepth() {
    return mragent_javaJNI.IImiBaseFrame_getDepth(swigCPtr, this);
  }

}
