/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

    import com.sximi.mragent.*;
    import com.sximi.mragent.ImiBodySkeleton;

public class IImiImageFrame extends IImiBaseFrame {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IImiImageFrame(long cPtr, boolean cMemoryOwn) {
    super(mragent_javaJNI.IImiImageFrame_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IImiImageFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        mragent_javaJNI.delete_IImiImageFrame(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public int getPixelFormat() {
    return mragent_javaJNI.IImiImageFrame_getPixelFormat(swigCPtr, this);
  }

  public int getFps() {
    return mragent_javaJNI.IImiImageFrame_getFps(swigCPtr, this);
  }

  public void getData(java.nio.ByteBuffer array_ref) {
  assert (array_ref.isDirect() || array_ref.array()!=null) : "Buffer must not be null.";
    {
      mragent_javaJNI.IImiImageFrame_getData(swigCPtr, this, array_ref.isDirect(), array_ref.isDirect() ? array_ref : array_ref.array());
    }
  }

  public int getDataSize() {
    return mragent_javaJNI.IImiImageFrame_getDataSize(swigCPtr, this);
  }

  public String toString() {
    return mragent_javaJNI.IImiImageFrame_toString(swigCPtr, this);
  }

}
