/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

    import com.sximi.mragent.*;
    import com.sximi.mragent.ImiBodySkeleton;

public class IImiDepthSensor extends IImiBaseSensor {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IImiDepthSensor(long cPtr, boolean cMemoryOwn) {
    super(mragent_javaJNI.IImiDepthSensor_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IImiDepthSensor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        mragent_javaJNI.delete_IImiDepthSensor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IImiDepthSensor(IImiBaseDevice pDevice) {
    this(mragent_javaJNI.new_IImiDepthSensor(IImiBaseDevice.getCPtr(pDevice), pDevice), true);
  }

  public static IImiDepthSensor asMe(IImiBaseSensor p) {
    long cPtr = mragent_javaJNI.IImiDepthSensor_asMe(IImiBaseSensor.getCPtr(p), p);
    return (cPtr == 0) ? null : new IImiDepthSensor(cPtr, true);
  }

  public String toString() {
    return mragent_javaJNI.IImiDepthSensor_toString(swigCPtr, this);
  }

}
