/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

    import com.sximi.mragent.*;
    import com.sximi.mragent.ImiBodySkeleton;

public class IImiBaseSensor {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected IImiBaseSensor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IImiBaseSensor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_javaJNI.delete_IImiBaseSensor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int getSensorType() {
    return mragent_javaJNI.IImiBaseSensor_getSensorType(swigCPtr, this);
  }

  public int start(int startFlags) {
    return mragent_javaJNI.IImiBaseSensor_start__SWIG_0(swigCPtr, this, startFlags);
  }

  public int start() {
    return mragent_javaJNI.IImiBaseSensor_start__SWIG_1(swigCPtr, this);
  }

  public int stop() {
    return mragent_javaJNI.IImiBaseSensor_stop(swigCPtr, this);
  }

  public int release() {
    return mragent_javaJNI.IImiBaseSensor_release(swigCPtr, this);
  }

  public boolean isStarted() {
    return mragent_javaJNI.IImiBaseSensor_isStarted(swigCPtr, this);
  }

  public IImiBaseFrame readFrame(int timeout) {
    long cPtr = mragent_javaJNI.IImiBaseSensor_readFrame__SWIG_0(swigCPtr, this, timeout);
    return (cPtr == 0) ? null : new IImiBaseFrame(cPtr, true);
  }

  public IImiBaseFrame readFrame() {
    long cPtr = mragent_javaJNI.IImiBaseSensor_readFrame__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new IImiBaseFrame(cPtr, true);
  }

  public int getWidth() {
    return mragent_javaJNI.IImiBaseSensor_getWidth(swigCPtr, this);
  }

  public int getHeight() {
    return mragent_javaJNI.IImiBaseSensor_getHeight(swigCPtr, this);
  }

  public int getDepth() {
    return mragent_javaJNI.IImiBaseSensor_getDepth(swigCPtr, this);
  }

  public void setWidth(int value) {
    mragent_javaJNI.IImiBaseSensor_setWidth(swigCPtr, this, value);
  }

  public void setHeight(int value) {
    mragent_javaJNI.IImiBaseSensor_setHeight(swigCPtr, this, value);
  }

  public void setDepth(int value) {
    mragent_javaJNI.IImiBaseSensor_setDepth(swigCPtr, this, value);
  }

}
