/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

    import com.sximi.mragent.*;
    import com.sximi.mragent.ImiBodySkeleton;

public class IImiColorFrame extends IImiImageFrame {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IImiColorFrame(long cPtr, boolean cMemoryOwn) {
    super(mragent_javaJNI.IImiColorFrame_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IImiColorFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        mragent_javaJNI.delete_IImiColorFrame(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IImiColorFrame(int dataSize) {
    this(mragent_javaJNI.new_IImiColorFrame(dataSize), true);
  }

  public static IImiColorFrame asMe(IImiBaseFrame p) {
    long cPtr = mragent_javaJNI.IImiColorFrame_asMe(IImiBaseFrame.getCPtr(p), p);
    return (cPtr == 0) ? null : new IImiColorFrame(cPtr, true);
  }

  public void getData(java.nio.ByteBuffer array_ref) {
  assert (array_ref.isDirect() || array_ref.array()!=null) : "Buffer must not be null.";
    {
      mragent_javaJNI.IImiColorFrame_getData(swigCPtr, this, array_ref.isDirect(), array_ref.isDirect() ? array_ref : array_ref.array());
    }
  }

  public int getDataSize() {
    return mragent_javaJNI.IImiColorFrame_getDataSize(swigCPtr, this);
  }

  public void release() {
    mragent_javaJNI.IImiColorFrame_release(swigCPtr, this);
  }

}
