/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

    import com.sximi.mragent.*;
    import com.sximi.mragent.ImiBodySkeleton;

public class IImiIRFrame extends IImiImageFrame {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IImiIRFrame(long cPtr, boolean cMemoryOwn) {
    super(mragent_javaJNI.IImiIRFrame_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IImiIRFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        mragent_javaJNI.delete_IImiIRFrame(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static IImiIRFrame asMe(IImiBaseFrame p) {
    long cPtr = mragent_javaJNI.IImiIRFrame_asMe(IImiBaseFrame.getCPtr(p), p);
    return (cPtr == 0) ? null : new IImiIRFrame(cPtr, true);
  }

  public void getRgbData(java.nio.ByteBuffer array_ref) {
  assert (array_ref.isDirect() || array_ref.array()!=null) : "Buffer must not be null.";
    {
      mragent_javaJNI.IImiIRFrame_getRgbData(swigCPtr, this, array_ref.isDirect(), array_ref.isDirect() ? array_ref : array_ref.array());
    }
  }

}
