/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

    import com.sximi.mragent.*;
    import com.sximi.mragent.ImiBodySkeleton;

public class IImiUserTrackSensor extends IImiBaseSensor {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IImiUserTrackSensor(long cPtr, boolean cMemoryOwn) {
    super(mragent_javaJNI.IImiUserTrackSensor_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IImiUserTrackSensor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        mragent_javaJNI.delete_IImiUserTrackSensor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IImiUserTrackSensor(IImiBaseDevice pDevice) {
    this(mragent_javaJNI.new_IImiUserTrackSensor(IImiBaseDevice.getCPtr(pDevice), pDevice), true);
  }

  public static IImiUserTrackSensor asMe(IImiBaseSensor p) {
    long cPtr = mragent_javaJNI.IImiUserTrackSensor_asMe(IImiBaseSensor.getCPtr(p), p);
    return (cPtr == 0) ? null : new IImiUserTrackSensor(cPtr, true);
  }

  public int start(int flags) {
    return mragent_javaJNI.IImiUserTrackSensor_start__SWIG_0(swigCPtr, this, flags);
  }

  public int start() {
    return mragent_javaJNI.IImiUserTrackSensor_start__SWIG_1(swigCPtr, this);
  }

  public int stop() {
    return mragent_javaJNI.IImiUserTrackSensor_stop(swigCPtr, this);
  }

  public IImiBaseFrame readFrame(int timeout) {
    long cPtr = mragent_javaJNI.IImiUserTrackSensor_readFrame__SWIG_0(swigCPtr, this, timeout);
    return (cPtr == 0) ? null : new IImiBaseFrame(cPtr, true);
  }

  public IImiBaseFrame readFrame() {
    long cPtr = mragent_javaJNI.IImiUserTrackSensor_readFrame__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new IImiBaseFrame(cPtr, true);
  }

  public final static class ImiUserTrackProperties {
    public final static int IMI_PROPERTY_USERTRACK_SKELETON_SMOOTH = 1;
    public final static int IMI_PROPERTY_USERTRACK_GROUND_CLEANUP = 2;
    public final static int IMI_PROPERTY_USERTRACK_OUPUT_FOREGROUND = 3;
    public final static int IMI_PROPERTY_USERTRACK_OUPUT_SEG_MASK = 4;
    public final static int IMI_PROPERTY_USERTRACK_GROUND_EQUATION = 5;
    public final static int IMI_PROPERTY_USERTRACK_OUPUT_PSCTRL = 6;
  }

  public final static class ImiUserTrackAlgorithmMode {
    public final static int IMI_TRACK_MODE_BODY = 0;
    public final static int IMI_TRACK_MODE_FACE = 1;
    public final static int IMI_TRACK_MODE_HAND = 2;
    public final static int IMI_TRACK_MODE_ECHO = 3;
    public final static int IMI_TRACK_MODE_SEGM = 4;
    public final static int IMI_TRACK_MODE_RGBM = 5;
    public final static int IMI_TRACK_MODE_RGBO = 6;
  }

}
