/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

    import com.sximi.mragent.*;
    import com.sximi.mragent.ImiBodySkeleton;

public class IImiCameraIntrinsicProperty extends IImiDeviceProperty {
  private transient long swigCPtr;

  public IImiCameraIntrinsicProperty(long cPtr, boolean cMemoryOwn) {
    super(mragent_javaJNI.IImiCameraIntrinsicProperty_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(IImiCameraIntrinsicProperty obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(IImiCameraIntrinsicProperty obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_javaJNI.delete_IImiCameraIntrinsicProperty(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IImiCameraIntrinsicProperty() {
    this(mragent_javaJNI.new_IImiCameraIntrinsicProperty__SWIG_0(), true);
  }

  public IImiCameraIntrinsicProperty(ImiCameraIntrinsic v) {
    this(mragent_javaJNI.new_IImiCameraIntrinsicProperty__SWIG_1(ImiCameraIntrinsic.getCPtr(v), v), true);
  }

  public void set(ImiCameraIntrinsic val) {
    mragent_javaJNI.IImiCameraIntrinsicProperty_set(swigCPtr, this, ImiCameraIntrinsic.getCPtr(val), val);
  }

  public ImiCameraIntrinsic get() {
    return new ImiCameraIntrinsic(mragent_javaJNI.IImiCameraIntrinsicProperty_get(swigCPtr, this), true);
  }

  public int dataSize() {
    return mragent_javaJNI.IImiCameraIntrinsicProperty_dataSize(swigCPtr, this);
  }

}
