/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

    import com.sximi.mragent.*;
    import com.sximi.mragent.ImiBodySkeleton;

public class IImiColorSensor extends IImiBaseSensor {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IImiColorSensor(long cPtr, boolean cMemoryOwn) {
    super(mragent_javaJNI.IImiColorSensor_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IImiColorSensor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        mragent_javaJNI.delete_IImiColorSensor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IImiColorSensor(IImiBaseDevice pDevice) {
    this(mragent_javaJNI.new_IImiColorSensor(IImiBaseDevice.getCPtr(pDevice), pDevice), true);
  }

  public static IImiColorSensor asMe(IImiBaseSensor p) {
    long cPtr = mragent_javaJNI.IImiColorSensor_asMe(IImiBaseSensor.getCPtr(p), p);
    return (cPtr == 0) ? null : new IImiColorSensor(cPtr, true);
  }

  public int start(int startFlags) {
    return mragent_javaJNI.IImiColorSensor_start__SWIG_0(swigCPtr, this, startFlags);
  }

  public int start() {
    return mragent_javaJNI.IImiColorSensor_start__SWIG_1(swigCPtr, this);
  }

  public int stop() {
    return mragent_javaJNI.IImiColorSensor_stop(swigCPtr, this);
  }

  public IImiBaseFrame readFrame(int timeout) {
    long cPtr = mragent_javaJNI.IImiColorSensor_readFrame__SWIG_0(swigCPtr, this, timeout);
    return (cPtr == 0) ? null : new IImiBaseFrame(cPtr, true);
  }

  public IImiBaseFrame readFrame() {
    long cPtr = mragent_javaJNI.IImiColorSensor_readFrame__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new IImiBaseFrame(cPtr, true);
  }

}
