/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

    import com.sximi.mragent.*;
    import com.sximi.mragent.ImiBodySkeleton;

public class IImiIRSensor extends IImiBaseSensor {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IImiIRSensor(long cPtr, boolean cMemoryOwn) {
    super(mragent_javaJNI.IImiIRSensor_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IImiIRSensor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        mragent_javaJNI.delete_IImiIRSensor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IImiIRSensor(IImiBaseDevice pDevice) {
    this(mragent_javaJNI.new_IImiIRSensor(IImiBaseDevice.getCPtr(pDevice), pDevice), true);
  }

  public static IImiIRSensor asMe(IImiBaseSensor p) {
    long cPtr = mragent_javaJNI.IImiIRSensor_asMe(IImiBaseSensor.getCPtr(p), p);
    return (cPtr == 0) ? null : new IImiIRSensor(cPtr, true);
  }

}
