/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

    import com.sximi.mragent.*;
    import com.sximi.mragent.ImiBodySkeleton;

public class IImiUserTrackFrame extends IImiBaseFrame {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected IImiUserTrackFrame(long cPtr, boolean cMemoryOwn) {
    super(mragent_javaJNI.IImiUserTrackFrame_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IImiUserTrackFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        mragent_javaJNI.delete_IImiUserTrackFrame(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public IImiUserTrackFrame(int fgSize) {
    this(mragent_javaJNI.new_IImiUserTrackFrame(fgSize), true);
  }

  public void release() {
    mragent_javaJNI.IImiUserTrackFrame_release(swigCPtr, this);
  }

  public static IImiUserTrackFrame asMe(IImiBaseFrame p) {
    long cPtr = mragent_javaJNI.IImiUserTrackFrame_asMe(IImiBaseFrame.getCPtr(p), p);
    return (cPtr == 0) ? null : new IImiUserTrackFrame(cPtr, true);
  }

  public ImiBodySkeleton getBodySkeleton() {
    return new ImiBodySkeleton(mragent_javaJNI.IImiUserTrackFrame_getBodySkeleton__SWIG_0(swigCPtr, this), true);
  }

  public boolean getBodySkeleton(ImiBodySkeleton sk) {
    return mragent_javaJNI.IImiUserTrackFrame_getBodySkeleton__SWIG_1(swigCPtr, this, ImiBodySkeleton.getCPtr(sk), sk);
  }

  public ImiHandSkeleton getHandSkeleton() {
    return new ImiHandSkeleton(mragent_javaJNI.IImiUserTrackFrame_getHandSkeleton(swigCPtr, this), true);
  }

  public ImiForegroundData getForegroundInfo() {
    return new ImiForegroundData(mragent_javaJNI.IImiUserTrackFrame_getForegroundInfo(swigCPtr, this), true);
  }

  public int getForegroundData(java.nio.ByteBuffer array_ref) {
  assert (array_ref.isDirect() || array_ref.array()!=null) : "Buffer must not be null.";
    {
      return mragent_javaJNI.IImiUserTrackFrame_getForegroundData(swigCPtr, this, array_ref.isDirect(), array_ref.isDirect() ? array_ref : array_ref.array());
    }
  }

  public ImiMattingData getMattingInfo() {
    return new ImiMattingData(mragent_javaJNI.IImiUserTrackFrame_getMattingInfo(swigCPtr, this), true);
  }

  public void getMattingData(java.nio.ByteBuffer array_ref) {
  assert (array_ref.isDirect() || array_ref.array()!=null) : "Buffer must not be null.";
    {
      mragent_javaJNI.IImiUserTrackFrame_getMattingData(swigCPtr, this, array_ref.isDirect(), array_ref.isDirect() ? array_ref : array_ref.array());
    }
  }

  public ImiFaceFeatureData getFaceFeatureFrame() {
    return new ImiFaceFeatureData(mragent_javaJNI.IImiUserTrackFrame_getFaceFeatureFrame(swigCPtr, this), true);
  }

  public int getForegroundRgbData(java.nio.ByteBuffer array_ref, int mode) {
  assert (array_ref.isDirect() || array_ref.array()!=null) : "Buffer must not be null.";
    {
      return mragent_javaJNI.IImiUserTrackFrame_getForegroundRgbData(swigCPtr, this, array_ref.isDirect(), array_ref.isDirect() ? array_ref : array_ref.array(), mode);
    }
  }

  public int getForegroundArgbData(java.nio.ByteBuffer array_ref, int mode) {
  assert (array_ref.isDirect() || array_ref.array()!=null) : "Buffer must not be null.";
    {
      return mragent_javaJNI.IImiUserTrackFrame_getForegroundArgbData(swigCPtr, this, array_ref.isDirect(), array_ref.isDirect() ? array_ref : array_ref.array(), mode);
    }
  }

  public int getBodySkeletonData(java.nio.ByteBuffer array_ref) {
  assert (array_ref.isDirect() || array_ref.array()!=null) : "Buffer must not be null.";
    {
      return mragent_javaJNI.IImiUserTrackFrame_getBodySkeletonData(swigCPtr, this, array_ref.isDirect(), array_ref.isDirect() ? array_ref : array_ref.array());
    }
  }

}
