/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiBodySkeleton extends ImiData {
  private transient long swigCPtr;

  public ImiBodySkeleton(long cPtr, boolean cMemoryOwn) {
    super(mragent_data_javaJNI.ImiBodySkeleton_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiBodySkeleton obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiBodySkeleton obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiBodySkeleton(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setWidth(int value) {
    mragent_data_javaJNI.ImiBodySkeleton_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return mragent_data_javaJNI.ImiBodySkeleton_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    mragent_data_javaJNI.ImiBodySkeleton_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return mragent_data_javaJNI.ImiBodySkeleton_height_get(swigCPtr, this);
  }

  public void setFloorClipPlane(ImiVector4 value) {
    mragent_data_javaJNI.ImiBodySkeleton_floorClipPlane_set(swigCPtr, this, ImiVector4.getCPtr(value), value);
  }

  public ImiVector4 getFloorClipPlane() {
    long cPtr = mragent_data_javaJNI.ImiBodySkeleton_floorClipPlane_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImiVector4(cPtr, false);
  }

  public void setSkeletonDatas(ImiBodySkeletonData[] value) {
    mragent_data_javaJNI.ImiBodySkeleton_skeletonDatas_set(swigCPtr, this, value);
  }

  public ImiBodySkeletonData[] getSkeletonDatas() {
    return mragent_data_javaJNI.ImiBodySkeleton_skeletonDatas_get(swigCPtr, this);
}

  public String toString() {
    return mragent_data_javaJNI.ImiBodySkeleton_toString(swigCPtr, this);
  }

  public boolean empty() {
    return mragent_data_javaJNI.ImiBodySkeleton_empty(swigCPtr, this);
  }

  public ImiBodySkeleton() {
    this(mragent_data_javaJNI.new_ImiBodySkeleton(), true);
  }

  public ImiBodySkeletonData at(int index) {
    long cPtr = mragent_data_javaJNI.ImiBodySkeleton_at(swigCPtr, this, index);
    return (cPtr == 0) ? null : new ImiBodySkeletonData(cPtr, false);
  }

  public ImiBodySkeletonData atBodySkeleton(int index) {
    long cPtr = mragent_data_javaJNI.ImiBodySkeleton_atBodySkeleton(swigCPtr, this, index);
    return (cPtr == 0) ? null : new ImiBodySkeletonData(cPtr, false);
  }

}
