/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiBodySkeletonData extends ImiData {
  private transient long swigCPtr;

  public ImiBodySkeletonData(long cPtr, boolean cMemoryOwn) {
    super(mragent_data_javaJNI.ImiBodySkeletonData_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiBodySkeletonData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiBodySkeletonData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiBodySkeletonData(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  static public class IMI_Rect {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    public IMI_Rect(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    public static long getCPtr(IMI_Rect obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    public static long swigRelease(IMI_Rect obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }
  
    @SuppressWarnings({"deprecation", "removal"})
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          mragent_data_javaJNI.delete_ImiBodySkeletonData_IMI_Rect(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setX(int value) {
      mragent_data_javaJNI.ImiBodySkeletonData_IMI_Rect_x_set(swigCPtr, this, value);
    }
  
    public int getX() {
      return mragent_data_javaJNI.ImiBodySkeletonData_IMI_Rect_x_get(swigCPtr, this);
    }
  
    public void setY(int value) {
      mragent_data_javaJNI.ImiBodySkeletonData_IMI_Rect_y_set(swigCPtr, this, value);
    }
  
    public int getY() {
      return mragent_data_javaJNI.ImiBodySkeletonData_IMI_Rect_y_get(swigCPtr, this);
    }
  
    public void setWidth(int value) {
      mragent_data_javaJNI.ImiBodySkeletonData_IMI_Rect_width_set(swigCPtr, this, value);
    }
  
    public int getWidth() {
      return mragent_data_javaJNI.ImiBodySkeletonData_IMI_Rect_width_get(swigCPtr, this);
    }
  
    public void setHeight(int value) {
      mragent_data_javaJNI.ImiBodySkeletonData_IMI_Rect_height_set(swigCPtr, this, value);
    }
  
    public int getHeight() {
      return mragent_data_javaJNI.ImiBodySkeletonData_IMI_Rect_height_get(swigCPtr, this);
    }
  
    public IMI_Rect() {
      this(mragent_data_javaJNI.new_ImiBodySkeletonData_IMI_Rect(), true);
    }
  
  }

  static public class ImiFaceFeature {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    public ImiFaceFeature(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    public static long getCPtr(ImiFaceFeature obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    public static long swigRelease(ImiFaceFeature obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }
  
    @SuppressWarnings({"deprecation", "removal"})
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          mragent_data_javaJNI.delete_ImiBodySkeletonData_ImiFaceFeature(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setFaceRect(ImiBodySkeletonData.IMI_Rect value) {
      mragent_data_javaJNI.ImiBodySkeletonData_ImiFaceFeature_faceRect_set(swigCPtr, this, ImiBodySkeletonData.IMI_Rect.getCPtr(value), value);
    }
  
    public ImiBodySkeletonData.IMI_Rect getFaceRect() {
      long cPtr = mragent_data_javaJNI.ImiBodySkeletonData_ImiFaceFeature_faceRect_get(swigCPtr, this);
      return (cPtr == 0) ? null : new ImiBodySkeletonData.IMI_Rect(cPtr, false);
    }
  
    public void setFaceSize(long value) {
      mragent_data_javaJNI.ImiBodySkeletonData_ImiFaceFeature_faceSize_set(swigCPtr, this, value);
    }
  
    public long getFaceSize() {
      return mragent_data_javaJNI.ImiBodySkeletonData_ImiFaceFeature_faceSize_get(swigCPtr, this);
    }
  
    public void setFaceID(long value) {
      mragent_data_javaJNI.ImiBodySkeletonData_ImiFaceFeature_faceID_set(swigCPtr, this, value);
    }
  
    public long getFaceID() {
      return mragent_data_javaJNI.ImiBodySkeletonData_ImiFaceFeature_faceID_get(swigCPtr, this);
    }
  
    public void setAge(long value) {
      mragent_data_javaJNI.ImiBodySkeletonData_ImiFaceFeature_age_set(swigCPtr, this, value);
    }
  
    public long getAge() {
      return mragent_data_javaJNI.ImiBodySkeletonData_ImiFaceFeature_age_get(swigCPtr, this);
    }
  
    public void setGender(long value) {
      mragent_data_javaJNI.ImiBodySkeletonData_ImiFaceFeature_gender_set(swigCPtr, this, value);
    }
  
    public long getGender() {
      return mragent_data_javaJNI.ImiBodySkeletonData_ImiFaceFeature_gender_get(swigCPtr, this);
    }
  
    public void setConfiendence(long value) {
      mragent_data_javaJNI.ImiBodySkeletonData_ImiFaceFeature_confiendence_set(swigCPtr, this, value);
    }
  
    public long getConfiendence() {
      return mragent_data_javaJNI.ImiBodySkeletonData_ImiFaceFeature_confiendence_get(swigCPtr, this);
    }
  
    public void setFaceFeatures(float[] value) {
      mragent_data_javaJNI.ImiBodySkeletonData_ImiFaceFeature_faceFeatures_set(swigCPtr, this, value);
    }
  
    public float[] getFaceFeatures() {
      return mragent_data_javaJNI.ImiBodySkeletonData_ImiFaceFeature_faceFeatures_get(swigCPtr, this);
    }
  
    public ImiFaceFeature() {
      this(mragent_data_javaJNI.new_ImiBodySkeletonData_ImiFaceFeature(), true);
    }
  
  }

  static public class ImiClothesFeature {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    public ImiClothesFeature(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    public static long getCPtr(ImiClothesFeature obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    public static long swigRelease(ImiClothesFeature obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }
  
    @SuppressWarnings({"deprecation", "removal"})
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          mragent_data_javaJNI.delete_ImiBodySkeletonData_ImiClothesFeature(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setClothesFeatures(float[] value) {
      mragent_data_javaJNI.ImiBodySkeletonData_ImiClothesFeature_clothesFeatures_set(swigCPtr, this, value);
    }
  
    public float[] getClothesFeatures() {
      return mragent_data_javaJNI.ImiBodySkeletonData_ImiClothesFeature_clothesFeatures_get(swigCPtr, this);
    }
  
    public ImiClothesFeature() {
      this(mragent_data_javaJNI.new_ImiBodySkeletonData_ImiClothesFeature(), true);
    }
  
  }

  static public class ImiFeature {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    public ImiFeature(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    public static long getCPtr(ImiFeature obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    public static long swigRelease(ImiFeature obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }
  
    @SuppressWarnings({"deprecation", "removal"})
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          mragent_data_javaJNI.delete_ImiBodySkeletonData_ImiFeature(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setFaceFeatureFlags(short value) {
      mragent_data_javaJNI.ImiBodySkeletonData_ImiFeature_faceFeatureFlags_set(swigCPtr, this, value);
    }
  
    public short getFaceFeatureFlags() {
      return mragent_data_javaJNI.ImiBodySkeletonData_ImiFeature_faceFeatureFlags_get(swigCPtr, this);
    }
  
    public void setClothesFeatureFlags(short value) {
      mragent_data_javaJNI.ImiBodySkeletonData_ImiFeature_clothesFeatureFlags_set(swigCPtr, this, value);
    }
  
    public short getClothesFeatureFlags() {
      return mragent_data_javaJNI.ImiBodySkeletonData_ImiFeature_clothesFeatureFlags_get(swigCPtr, this);
    }
  
    public void setRev(short[] value) {
      mragent_data_javaJNI.ImiBodySkeletonData_ImiFeature_rev_set(swigCPtr, this, value);
    }
  
    public short[] getRev() {
      return mragent_data_javaJNI.ImiBodySkeletonData_ImiFeature_rev_get(swigCPtr, this);
    }
  
    public void setFaceFeature(ImiBodySkeletonData.ImiFaceFeature value) {
      mragent_data_javaJNI.ImiBodySkeletonData_ImiFeature_faceFeature_set(swigCPtr, this, ImiBodySkeletonData.ImiFaceFeature.getCPtr(value), value);
    }
  
    public ImiBodySkeletonData.ImiFaceFeature getFaceFeature() {
      long cPtr = mragent_data_javaJNI.ImiBodySkeletonData_ImiFeature_faceFeature_get(swigCPtr, this);
      return (cPtr == 0) ? null : new ImiBodySkeletonData.ImiFaceFeature(cPtr, false);
    }
  
    public void setClothesFeature(ImiBodySkeletonData.ImiClothesFeature value) {
      mragent_data_javaJNI.ImiBodySkeletonData_ImiFeature_clothesFeature_set(swigCPtr, this, ImiBodySkeletonData.ImiClothesFeature.getCPtr(value), value);
    }
  
    public ImiBodySkeletonData.ImiClothesFeature getClothesFeature() {
      long cPtr = mragent_data_javaJNI.ImiBodySkeletonData_ImiFeature_clothesFeature_get(swigCPtr, this);
      return (cPtr == 0) ? null : new ImiBodySkeletonData.ImiClothesFeature(cPtr, false);
    }
  
    public ImiFeature() {
      this(mragent_data_javaJNI.new_ImiBodySkeletonData_ImiFeature(), true);
    }
  
  }

  public void setTrackingState(int value) {
    mragent_data_javaJNI.ImiBodySkeletonData_trackingState_set(swigCPtr, this, value);
  }

  public int getTrackingState() {
    return mragent_data_javaJNI.ImiBodySkeletonData_trackingState_get(swigCPtr, this);
  }

  public void setTrackingID(long value) {
    mragent_data_javaJNI.ImiBodySkeletonData_trackingID_set(swigCPtr, this, value);
  }

  public long getTrackingID() {
    return mragent_data_javaJNI.ImiBodySkeletonData_trackingID_get(swigCPtr, this);
  }

  public void setCenterPosition(ImiVector4 value) {
    mragent_data_javaJNI.ImiBodySkeletonData_centerPosition_set(swigCPtr, this, ImiVector4.getCPtr(value), value);
  }

  public ImiVector4 getCenterPosition() {
    long cPtr = mragent_data_javaJNI.ImiBodySkeletonData_centerPosition_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImiVector4(cPtr, false);
  }

  public void setSkeletonPositions(ImiVector4[] value) {
    mragent_data_javaJNI.ImiBodySkeletonData_skeletonPositions_set(swigCPtr, this, value);
  }

  public ImiVector4[] getSkeletonPositions() {
    return mragent_data_javaJNI.ImiBodySkeletonData_skeletonPositions_get(swigCPtr, this);
}

  public void setSkeletonPositionTrackingStates(int[] value) {
    mragent_data_javaJNI.ImiBodySkeletonData_skeletonPositionTrackingStates_set(swigCPtr, this, value);
  }

  public int[] getSkeletonPositionTrackingStates() {
    return mragent_data_javaJNI.ImiBodySkeletonData_skeletonPositionTrackingStates_get(swigCPtr, this);
}

  public void setQualityFlags(long value) {
    mragent_data_javaJNI.ImiBodySkeletonData_qualityFlags_set(swigCPtr, this, value);
  }

  public long getQualityFlags() {
    return mragent_data_javaJNI.ImiBodySkeletonData_qualityFlags_get(swigCPtr, this);
  }

  public void setUpSkeletonsOrientationState(int value) {
    mragent_data_javaJNI.ImiBodySkeletonData_upSkeletonsOrientationState_set(swigCPtr, this, value);
  }

  public int getUpSkeletonsOrientationState() {
    return mragent_data_javaJNI.ImiBodySkeletonData_upSkeletonsOrientationState_get(swigCPtr, this);
  }

  public void setUpSkeletonsOrientation(ImiMat3f value) {
    mragent_data_javaJNI.ImiBodySkeletonData_upSkeletonsOrientation_set(swigCPtr, this, ImiMat3f.getCPtr(value), value);
  }

  public ImiMat3f getUpSkeletonsOrientation() {
    long cPtr = mragent_data_javaJNI.ImiBodySkeletonData_upSkeletonsOrientation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImiMat3f(cPtr, false);
  }

  public void setDownSkeletonsOrientationState(int value) {
    mragent_data_javaJNI.ImiBodySkeletonData_downSkeletonsOrientationState_set(swigCPtr, this, value);
  }

  public int getDownSkeletonsOrientationState() {
    return mragent_data_javaJNI.ImiBodySkeletonData_downSkeletonsOrientationState_get(swigCPtr, this);
  }

  public void setDownSkeletonsOrientation(ImiMat3f value) {
    mragent_data_javaJNI.ImiBodySkeletonData_downSkeletonsOrientation_set(swigCPtr, this, ImiMat3f.getCPtr(value), value);
  }

  public ImiMat3f getDownSkeletonsOrientation() {
    long cPtr = mragent_data_javaJNI.ImiBodySkeletonData_downSkeletonsOrientation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImiMat3f(cPtr, false);
  }

  public void setSkeletonOrientationStates(int[] value) {
    mragent_data_javaJNI.ImiBodySkeletonData_skeletonOrientationStates_set(swigCPtr, this, value);
  }

  public int[] getSkeletonOrientationStates() {
    return mragent_data_javaJNI.ImiBodySkeletonData_skeletonOrientationStates_get(swigCPtr, this);
}

  public void setSkeletonOrientations(ImiSkeletonOrientationData[] value) {
    mragent_data_javaJNI.ImiBodySkeletonData_skeletonOrientations_set(swigCPtr, this, value);
  }

  public ImiSkeletonOrientationData[] getSkeletonOrientations() {
    return mragent_data_javaJNI.ImiBodySkeletonData_skeletonOrientations_get(swigCPtr, this);
}

  public void setPoseState(int value) {
    mragent_data_javaJNI.ImiBodySkeletonData_poseState_set(swigCPtr, this, value);
  }

  public int getPoseState() {
    return mragent_data_javaJNI.ImiBodySkeletonData_poseState_get(swigCPtr, this);
  }

  public void setFeature(ImiBodySkeletonData.ImiFeature value) {
    mragent_data_javaJNI.ImiBodySkeletonData_feature_set(swigCPtr, this, ImiBodySkeletonData.ImiFeature.getCPtr(value), value);
  }

  public ImiBodySkeletonData.ImiFeature getFeature() {
    long cPtr = mragent_data_javaJNI.ImiBodySkeletonData_feature_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImiBodySkeletonData.ImiFeature(cPtr, false);
  }

  public void setHandState(int value) {
    mragent_data_javaJNI.ImiBodySkeletonData_handState_set(swigCPtr, this, value);
  }

  public int getHandState() {
    return mragent_data_javaJNI.ImiBodySkeletonData_handState_get(swigCPtr, this);
  }

  public void setHandRect(ImiBodySkeletonData.IMI_Rect value) {
    mragent_data_javaJNI.ImiBodySkeletonData_handRect_set(swigCPtr, this, ImiBodySkeletonData.IMI_Rect.getCPtr(value), value);
  }

  public ImiBodySkeletonData.IMI_Rect getHandRect() {
    long cPtr = mragent_data_javaJNI.ImiBodySkeletonData_handRect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImiBodySkeletonData.IMI_Rect(cPtr, false);
  }

  public void getVertexes(SWIGTYPE_p_float array_ref, int array_len) {
    mragent_data_javaJNI.ImiBodySkeletonData_getVertexes(swigCPtr, this, SWIGTYPE_p_float.getCPtr(array_ref), array_len);
  }

  public static int[] getSkeletonLinkIndexes() {
    return mragent_data_javaJNI.ImiBodySkeletonData_getSkeletonLinkIndexes();
}

  public String toString() {
    return mragent_data_javaJNI.ImiBodySkeletonData_toString(swigCPtr, this);
  }

  public ImiBodySkeletonData() {
    this(mragent_data_javaJNI.new_ImiBodySkeletonData(), true);
  }

  public final static class ImiBodySkeletonPositionIndex {
    public final static int IMI_BODY_SKELETON_HIP_CENTER = 0;
    public final static int IMI_BODY_SKELETON_SPINE = 1;
    public final static int IMI_BODY_SKELETON_SHOULDER_CENTER = 2;
    public final static int IMI_BODY_SKELETON_HEAD = 3;
    public final static int IMI_BODY_SKELETON_SHOULDER_LEFT = 4;
    public final static int IMI_BODY_SKELETON_ELBOW_LEFT = 5;
    public final static int IMI_BODY_SKELETON_WRIST_LEFT = 6;
    public final static int IMI_BODY_SKELETON_HAND_LEFT = 7;
    public final static int IMI_BODY_SKELETON_SHOULDER_RIGHT = 8;
    public final static int IMI_BODY_SKELETON_ELBOW_RIGHT = 9;
    public final static int IMI_BODY_SKELETON_WRIST_RIGHT = 10;
    public final static int IMI_BODY_SKELETON_HAND_RIGHT = 11;
    public final static int IMI_BODY_SKELETON_HIP_LEFT = 12;
    public final static int IMI_BODY_SKELETON_KNEE_LEFT = 13;
    public final static int IMI_BODY_SKELETON_ANKLE_LEFT = 14;
    public final static int IMI_BODY_SKELETON_FOOT_LEFT = 15;
    public final static int IMI_BODY_SKELETON_HIP_RIGHT = 16;
    public final static int IMI_BODY_SKELETON_KNEE_RIGHT = 17;
    public final static int IMI_BODY_SKELETON_ANKLE_RIGHT = 18;
    public final static int IMI_BODY_SKELETON_FOOT_RIGHT = 19;
    public final static int IMI_BODY_SKELETON_COUNT = 20;
  }

  public final static class ImiBodySkeletonPositionTrackState {
    public final static int IMI_BODY_SKELETON_POSITION_NOT_TRACKED = 0;
    public final static int IMI_BODY_SKELETON_POSITION_INFERRED = 1;
    public final static int IMI_BODY_SKELETON_POSITION_TRACKED = 2;
  }

  public final static class ImiSkeletonOrientationState {
    public final static int IMI_SKELETON_ORIENTATION_AVAILABLE = 0;
    public final static int IMI_SKELETON_ORIENTATION_UNAVAILABLE = 1;
    public final static int IMI_SKELETON_ORIENTATION_UNDEFINED = 2;
  }

  public final static class ImiPoseState {
    public final static int IMI_POSE_UNSURE = 0;
    public final static int IMI_POSE_STAND = 1;
    public final static int IMI_POSE_SEATED = 2;
  }

  public final static class ImiHandState {
    public final static int IMI_HAND_UNSURE = 0;
    public final static int IMI_HAND_GRASP = 1;
    public final static int IMI_HAND_OPEN = 2;
  }

}
