/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiCameraIntrinsic extends ImiData {
  private transient long swigCPtr;

  public ImiCameraIntrinsic(long cPtr, boolean cMemoryOwn) {
    super(mragent_data_javaJNI.ImiCameraIntrinsic_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiCameraIntrinsic obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiCameraIntrinsic obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiCameraIntrinsic(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setFxParam(float value) {
    mragent_data_javaJNI.ImiCameraIntrinsic_fxParam_set(swigCPtr, this, value);
  }

  public float getFxParam() {
    return mragent_data_javaJNI.ImiCameraIntrinsic_fxParam_get(swigCPtr, this);
  }

  public void setFyParam(float value) {
    mragent_data_javaJNI.ImiCameraIntrinsic_fyParam_set(swigCPtr, this, value);
  }

  public float getFyParam() {
    return mragent_data_javaJNI.ImiCameraIntrinsic_fyParam_get(swigCPtr, this);
  }

  public void setCxParam(float value) {
    mragent_data_javaJNI.ImiCameraIntrinsic_cxParam_set(swigCPtr, this, value);
  }

  public float getCxParam() {
    return mragent_data_javaJNI.ImiCameraIntrinsic_cxParam_get(swigCPtr, this);
  }

  public void setCyParam(float value) {
    mragent_data_javaJNI.ImiCameraIntrinsic_cyParam_set(swigCPtr, this, value);
  }

  public float getCyParam() {
    return mragent_data_javaJNI.ImiCameraIntrinsic_cyParam_get(swigCPtr, this);
  }

  public void setK1Param(float value) {
    mragent_data_javaJNI.ImiCameraIntrinsic_k1Param_set(swigCPtr, this, value);
  }

  public float getK1Param() {
    return mragent_data_javaJNI.ImiCameraIntrinsic_k1Param_get(swigCPtr, this);
  }

  public void setK2Param(float value) {
    mragent_data_javaJNI.ImiCameraIntrinsic_k2Param_set(swigCPtr, this, value);
  }

  public float getK2Param() {
    return mragent_data_javaJNI.ImiCameraIntrinsic_k2Param_get(swigCPtr, this);
  }

  public void setK3Param(float value) {
    mragent_data_javaJNI.ImiCameraIntrinsic_k3Param_set(swigCPtr, this, value);
  }

  public float getK3Param() {
    return mragent_data_javaJNI.ImiCameraIntrinsic_k3Param_get(swigCPtr, this);
  }

  public void setP1Param(float value) {
    mragent_data_javaJNI.ImiCameraIntrinsic_p1Param_set(swigCPtr, this, value);
  }

  public float getP1Param() {
    return mragent_data_javaJNI.ImiCameraIntrinsic_p1Param_get(swigCPtr, this);
  }

  public void setP2Param(float value) {
    mragent_data_javaJNI.ImiCameraIntrinsic_p2Param_set(swigCPtr, this, value);
  }

  public float getP2Param() {
    return mragent_data_javaJNI.ImiCameraIntrinsic_p2Param_get(swigCPtr, this);
  }

  public ImiCameraIntrinsic(float fx, float fy, float cx, float cy) {
    this(mragent_data_javaJNI.new_ImiCameraIntrinsic__SWIG_0(fx, fy, cx, cy), true);
  }

  public ImiCameraIntrinsic(float fx, float fy, float cx) {
    this(mragent_data_javaJNI.new_ImiCameraIntrinsic__SWIG_1(fx, fy, cx), true);
  }

  public ImiCameraIntrinsic(float fx, float fy) {
    this(mragent_data_javaJNI.new_ImiCameraIntrinsic__SWIG_2(fx, fy), true);
  }

  public ImiCameraIntrinsic(float fx) {
    this(mragent_data_javaJNI.new_ImiCameraIntrinsic__SWIG_3(fx), true);
  }

  public ImiCameraIntrinsic() {
    this(mragent_data_javaJNI.new_ImiCameraIntrinsic__SWIG_4(), true);
  }

  public String toString() {
    return mragent_data_javaJNI.ImiCameraIntrinsic_toString(swigCPtr, this);
  }

}
