/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiDeviceAttribute extends ImiData {
  private transient long swigCPtr;

  public ImiDeviceAttribute(long cPtr, boolean cMemoryOwn) {
    super(mragent_data_javaJNI.ImiDeviceAttribute_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiDeviceAttribute obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiDeviceAttribute obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiDeviceAttribute(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setVendorId(int value) {
    mragent_data_javaJNI.ImiDeviceAttribute_vendorId_set(swigCPtr, this, value);
  }

  public int getVendorId() {
    return mragent_data_javaJNI.ImiDeviceAttribute_vendorId_get(swigCPtr, this);
  }

  public void setProductId(int value) {
    mragent_data_javaJNI.ImiDeviceAttribute_productId_set(swigCPtr, this, value);
  }

  public int getProductId() {
    return mragent_data_javaJNI.ImiDeviceAttribute_productId_get(swigCPtr, this);
  }

  public void setUri(String value) {
    mragent_data_javaJNI.ImiDeviceAttribute_uri_set(swigCPtr, this, value);
  }

  public String getUri() {
    return mragent_data_javaJNI.ImiDeviceAttribute_uri_get(swigCPtr, this);
  }

  public void setEnableUVC(boolean value) {
    mragent_data_javaJNI.ImiDeviceAttribute_enableUVC_set(swigCPtr, this, value);
  }

  public boolean getEnableUVC() {
    return mragent_data_javaJNI.ImiDeviceAttribute_enableUVC_get(swigCPtr, this);
  }

  public ImiDeviceAttribute(int vendorId, int productId, String uri, boolean enableUVC) {
    this(mragent_data_javaJNI.new_ImiDeviceAttribute__SWIG_0(vendorId, productId, uri, enableUVC), true);
  }

  public ImiDeviceAttribute(int vendorId, int productId, String uri) {
    this(mragent_data_javaJNI.new_ImiDeviceAttribute__SWIG_1(vendorId, productId, uri), true);
  }

  public ImiDeviceAttribute(int vendorId, int productId) {
    this(mragent_data_javaJNI.new_ImiDeviceAttribute__SWIG_2(vendorId, productId), true);
  }

  public ImiDeviceAttribute(int vendorId) {
    this(mragent_data_javaJNI.new_ImiDeviceAttribute__SWIG_3(vendorId), true);
  }

  public ImiDeviceAttribute() {
    this(mragent_data_javaJNI.new_ImiDeviceAttribute__SWIG_4(), true);
  }

  public String toString() {
    return mragent_data_javaJNI.ImiDeviceAttribute_toString(swigCPtr, this);
  }

}
