/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiFaceFeatureVec extends ImiData {
  private transient long swigCPtr;

  public ImiFaceFeatureVec(long cPtr, boolean cMemoryOwn) {
    super(mragent_data_javaJNI.ImiFaceFeatureVec_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiFaceFeatureVec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiFaceFeatureVec obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiFaceFeatureVec(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setFaceFeatures(float[] value) {
    mragent_data_javaJNI.ImiFaceFeatureVec_faceFeatures_set(swigCPtr, this, value);
  }

  public float[] getFaceFeatures() {
    return mragent_data_javaJNI.ImiFaceFeatureVec_faceFeatures_get(swigCPtr, this);
  }

  public String toString() {
    return mragent_data_javaJNI.ImiFaceFeatureVec_toString(swigCPtr, this);
  }

  public ImiFaceFeatureVec() {
    this(mragent_data_javaJNI.new_ImiFaceFeatureVec(), true);
  }

}
