/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiFaceFeatureData extends ImiData {
  private transient long swigCPtr;

  public ImiFaceFeatureData(long cPtr, boolean cMemoryOwn) {
    super(mragent_data_javaJNI.ImiFaceFeatureData_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiFaceFeatureData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiFaceFeatureData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiFaceFeatureData(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setTrackingID(long value) {
    mragent_data_javaJNI.ImiFaceFeatureData_trackingID_set(swigCPtr, this, value);
  }

  public long getTrackingID() {
    return mragent_data_javaJNI.ImiFaceFeatureData_trackingID_get(swigCPtr, this);
  }

  public void setBFeatureValid(short value) {
    mragent_data_javaJNI.ImiFaceFeatureData_bFeatureValid_set(swigCPtr, this, value);
  }

  public short getBFeatureValid() {
    return mragent_data_javaJNI.ImiFaceFeatureData_bFeatureValid_get(swigCPtr, this);
  }

  public void setFaceRect(ImiRect value) {
    mragent_data_javaJNI.ImiFaceFeatureData_faceRect_set(swigCPtr, this, ImiRect.getCPtr(value), value);
  }

  public ImiRect getFaceRect() {
    long cPtr = mragent_data_javaJNI.ImiFaceFeatureData_faceRect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImiRect(cPtr, false);
  }

  public void setFaceSize(long value) {
    mragent_data_javaJNI.ImiFaceFeatureData_faceSize_set(swigCPtr, this, value);
  }

  public long getFaceSize() {
    return mragent_data_javaJNI.ImiFaceFeatureData_faceSize_get(swigCPtr, this);
  }

  public void setFaceFeatures(ImiFaceFeatureVec value) {
    mragent_data_javaJNI.ImiFaceFeatureData_faceFeatures_set(swigCPtr, this, ImiFaceFeatureVec.getCPtr(value), value);
  }

  public ImiFaceFeatureVec getFaceFeatures() {
    long cPtr = mragent_data_javaJNI.ImiFaceFeatureData_faceFeatures_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImiFaceFeatureVec(cPtr, false);
  }

  public String toString() {
    return mragent_data_javaJNI.ImiFaceFeatureData_toString(swigCPtr, this);
  }

  public ImiFaceFeatureData() {
    this(mragent_data_javaJNI.new_ImiFaceFeatureData(), true);
  }

}
