/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiFaceDetectData extends ImiData {
  private transient long swigCPtr;

  public ImiFaceDetectData(long cPtr, boolean cMemoryOwn) {
    super(mragent_data_javaJNI.ImiFaceDetectData_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiFaceDetectData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiFaceDetectData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiFaceDetectData(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ImiFaceDetectData() {
    this(mragent_data_javaJNI.new_ImiFaceDetectData(), true);
  }

  public void setRect(ImiRect value) {
    mragent_data_javaJNI.ImiFaceDetectData_rect_set(swigCPtr, this, ImiRect.getCPtr(value), value);
  }

  public ImiRect getRect() {
    long cPtr = mragent_data_javaJNI.ImiFaceDetectData_rect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImiRect(cPtr, false);
  }

  public void setLandmark(ImiPoint2D[] value) {
    mragent_data_javaJNI.ImiFaceDetectData_landmark_set(swigCPtr, this, value);
  }

  public ImiPoint2D[] getLandmark() {
    return mragent_data_javaJNI.ImiFaceDetectData_landmark_get(swigCPtr, this);
}

  public void setDepth(float value) {
    mragent_data_javaJNI.ImiFaceDetectData_depth_set(swigCPtr, this, value);
  }

  public float getDepth() {
    return mragent_data_javaJNI.ImiFaceDetectData_depth_get(swigCPtr, this);
  }

  public void setDepthLivenessScore(float value) {
    mragent_data_javaJNI.ImiFaceDetectData_depthLivenessScore_set(swigCPtr, this, value);
  }

  public float getDepthLivenessScore() {
    return mragent_data_javaJNI.ImiFaceDetectData_depthLivenessScore_get(swigCPtr, this);
  }

  public void setIrLivenessScore(float value) {
    mragent_data_javaJNI.ImiFaceDetectData_irLivenessScore_set(swigCPtr, this, value);
  }

  public float getIrLivenessScore() {
    return mragent_data_javaJNI.ImiFaceDetectData_irLivenessScore_get(swigCPtr, this);
  }

  public void setLivenessScore(float value) {
    mragent_data_javaJNI.ImiFaceDetectData_livenessScore_set(swigCPtr, this, value);
  }

  public float getLivenessScore() {
    return mragent_data_javaJNI.ImiFaceDetectData_livenessScore_get(swigCPtr, this);
  }

  public void setBlur(short value) {
    mragent_data_javaJNI.ImiFaceDetectData_blur_set(swigCPtr, this, value);
  }

  public short getBlur() {
    return mragent_data_javaJNI.ImiFaceDetectData_blur_get(swigCPtr, this);
  }

  public void setLight(short value) {
    mragent_data_javaJNI.ImiFaceDetectData_light_set(swigCPtr, this, value);
  }

  public short getLight() {
    return mragent_data_javaJNI.ImiFaceDetectData_light_get(swigCPtr, this);
  }

  public void setCover(short value) {
    mragent_data_javaJNI.ImiFaceDetectData_cover_set(swigCPtr, this, value);
  }

  public short getCover() {
    return mragent_data_javaJNI.ImiFaceDetectData_cover_get(swigCPtr, this);
  }

  public void setAngle(short value) {
    mragent_data_javaJNI.ImiFaceDetectData_angle_set(swigCPtr, this, value);
  }

  public short getAngle() {
    return mragent_data_javaJNI.ImiFaceDetectData_angle_get(swigCPtr, this);
  }

  public void setEyeDistanceStatus(short value) {
    mragent_data_javaJNI.ImiFaceDetectData_eyeDistanceStatus_set(swigCPtr, this, value);
  }

  public short getEyeDistanceStatus() {
    return mragent_data_javaJNI.ImiFaceDetectData_eyeDistanceStatus_get(swigCPtr, this);
  }

  public void setExpression(short value) {
    mragent_data_javaJNI.ImiFaceDetectData_expression_set(swigCPtr, this, value);
  }

  public short getExpression() {
    return mragent_data_javaJNI.ImiFaceDetectData_expression_get(swigCPtr, this);
  }

  public void setMoreFace(short value) {
    mragent_data_javaJNI.ImiFaceDetectData_moreFace_set(swigCPtr, this, value);
  }

  public short getMoreFace() {
    return mragent_data_javaJNI.ImiFaceDetectData_moreFace_get(swigCPtr, this);
  }

  public void setOpenMouth(short value) {
    mragent_data_javaJNI.ImiFaceDetectData_openMouth_set(swigCPtr, this, value);
  }

  public short getOpenMouth() {
    return mragent_data_javaJNI.ImiFaceDetectData_openMouth_get(swigCPtr, this);
  }

  public void setCloseEye(short value) {
    mragent_data_javaJNI.ImiFaceDetectData_closeEye_set(swigCPtr, this, value);
  }

  public short getCloseEye() {
    return mragent_data_javaJNI.ImiFaceDetectData_closeEye_get(swigCPtr, this);
  }

  public void setOk(short value) {
    mragent_data_javaJNI.ImiFaceDetectData_ok_set(swigCPtr, this, value);
  }

  public short getOk() {
    return mragent_data_javaJNI.ImiFaceDetectData_ok_get(swigCPtr, this);
  }

  public void setEyeDistance(float value) {
    mragent_data_javaJNI.ImiFaceDetectData_eyeDistance_set(swigCPtr, this, value);
  }

  public float getEyeDistance() {
    return mragent_data_javaJNI.ImiFaceDetectData_eyeDistance_get(swigCPtr, this);
  }

  public void setRoll(float value) {
    mragent_data_javaJNI.ImiFaceDetectData_roll_set(swigCPtr, this, value);
  }

  public float getRoll() {
    return mragent_data_javaJNI.ImiFaceDetectData_roll_get(swigCPtr, this);
  }

  public void setPitch(float value) {
    mragent_data_javaJNI.ImiFaceDetectData_pitch_set(swigCPtr, this, value);
  }

  public float getPitch() {
    return mragent_data_javaJNI.ImiFaceDetectData_pitch_get(swigCPtr, this);
  }

  public void setYaw(float value) {
    mragent_data_javaJNI.ImiFaceDetectData_yaw_set(swigCPtr, this, value);
  }

  public float getYaw() {
    return mragent_data_javaJNI.ImiFaceDetectData_yaw_get(swigCPtr, this);
  }

  public void setQualityScore(float value) {
    mragent_data_javaJNI.ImiFaceDetectData_qualityScore_set(swigCPtr, this, value);
  }

  public float getQualityScore() {
    return mragent_data_javaJNI.ImiFaceDetectData_qualityScore_get(swigCPtr, this);
  }

  public String toString() {
    return mragent_data_javaJNI.ImiFaceDetectData_toString(swigCPtr, this);
  }

}
