/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public final class ImiGestureType {
  public final static int IMI_GESTURE_NONE = 0;
  public final static int IMI_GESTURE_LEFT_HAND_WAVE = IMI_GESTURE_NONE + 1;
  public final static int IMI_GESTURE_RIGHT_HAND_WAVE = IMI_GESTURE_LEFT_HAND_WAVE + 1;
  public final static int IMI_GESTURE_LEFT_HAND_SWIPE_LEFT = IMI_GESTURE_RIGHT_HAND_WAVE + 1;
  public final static int IMI_GESTURE_LEFT_HAND_SWIPE_RIGHT = IMI_GESTURE_LEFT_HAND_SWIPE_LEFT + 1;
  public final static int IMI_GESTURE_RIGHT_HAND_SWIPE_LEFT = IMI_GESTURE_LEFT_HAND_SWIPE_RIGHT + 1;
  public final static int IMI_GESTURE_RIGHT_HAND_SWIPE_RIGHT = IMI_GESTURE_RIGHT_HAND_SWIPE_LEFT + 1;
  public final static int IMI_GESTURE_LEFT_HAND_PUSH = IMI_GESTURE_RIGHT_HAND_SWIPE_RIGHT + 1;
  public final static int IMI_GESTURE_RIGHT_HAND_PUSH = IMI_GESTURE_LEFT_HAND_PUSH + 1;
  public final static int IMI_GESTURE_LEFT_HAND_HOOKUP = IMI_GESTURE_RIGHT_HAND_PUSH + 1;
  public final static int IMI_GESTURE_RIGHT_HAND_HOOKUP = IMI_GESTURE_LEFT_HAND_HOOKUP + 1;
  public final static int IMI_GESTURE_LEAN_FORWARD = IMI_GESTURE_RIGHT_HAND_HOOKUP + 1;
  public final static int IMI_GESTURE_LEAN_BACKWARD = IMI_GESTURE_LEAN_FORWARD + 1;
  public final static int IMI_GESTURE_LEAN_LEFT = IMI_GESTURE_LEAN_BACKWARD + 1;
  public final static int IMI_GESTURE_LEAN_RIGHT = IMI_GESTURE_LEAN_LEFT + 1;
  public final static int IMI_GESTURE_JUMP = IMI_GESTURE_LEAN_RIGHT + 1;
  public final static int IMI_GESTURE_SQUAT = IMI_GESTURE_JUMP + 1;
  public final static int IMI_GESTURE_WING = IMI_GESTURE_SQUAT + 1;
  public final static int IMI_GESTURE_RUN = IMI_GESTURE_WING + 1;
  public final static int IMI_GESTURE_ZOOM_OUT = IMI_GESTURE_RUN + 1;
  public final static int IMI_GESTURE_ZOOM_IN = IMI_GESTURE_ZOOM_OUT + 1;
  public final static int IMI_GESTURE_LEFT_HAND_OVER_HEAD = IMI_GESTURE_ZOOM_IN + 1;
  public final static int IMI_GESTURE_RIGHT_HAND_OVER_HEAD = IMI_GESTURE_LEFT_HAND_OVER_HEAD + 1;
  public final static int IMI_GESTURE_BOTH_HANDS_OVER_HEAD = IMI_GESTURE_RIGHT_HAND_OVER_HEAD + 1;
  public final static int IMI_GESTURE_BOTH_HANDS_BACK = IMI_GESTURE_BOTH_HANDS_OVER_HEAD + 1;
  public final static int IMI_GESTURE_LEFT_ARM_PAUSE = IMI_GESTURE_BOTH_HANDS_BACK + 1;
  public final static int IMI_GESTURE_RIGHT_ARM_PAUSE = IMI_GESTURE_LEFT_ARM_PAUSE + 1;
  public final static int IMI_GESTURE_LEFT_ARM_FORWARD = IMI_GESTURE_RIGHT_ARM_PAUSE + 1;
  public final static int IMI_GESTURE_RIGHT_ARM_FORWARD = IMI_GESTURE_LEFT_ARM_FORWARD + 1;
  public final static int IMI_GESTURE_BOTH_ARMS_FORWARD = IMI_GESTURE_RIGHT_ARM_FORWARD + 1;
  public final static int IMI_GESTURE_LEFT_ARM_LATERAL_RAISE = IMI_GESTURE_BOTH_ARMS_FORWARD + 1;
  public final static int IMI_GESTURE_RIGHT_ARM_LATERAL_RAISE = IMI_GESTURE_LEFT_ARM_LATERAL_RAISE + 1;
  public final static int IMI_GESTURE_BOTH_ARMS_LATERAL_RAISE = IMI_GESTURE_RIGHT_ARM_LATERAL_RAISE + 1;
  public final static int IMI_GESTURE_RIGHT_ARM_LATERAL_RAISE_LEFT_ARM_UP = IMI_GESTURE_BOTH_ARMS_LATERAL_RAISE + 1;
  public final static int IMI_GESTURE_RIGHT_ARM_UP_LEFT_ARM_LATERAL_RAISE = IMI_GESTURE_RIGHT_ARM_LATERAL_RAISE_LEFT_ARM_UP + 1;
  public final static int IMI_GESTURE_LEFT_KNEE_KICK = IMI_GESTURE_RIGHT_ARM_UP_LEFT_ARM_LATERAL_RAISE + 1;
  public final static int IMI_GESTURE_RIGHT_KNEE_KICK = IMI_GESTURE_LEFT_KNEE_KICK + 1;
  public final static int IMI_GESTURE_LEFT_KNEE_LIFT = IMI_GESTURE_RIGHT_KNEE_KICK + 1;
  public final static int IMI_GESTURE_RIGHT_KNEE_LIFT = IMI_GESTURE_LEFT_KNEE_LIFT + 1;
  public final static int IMI_GESTURE_LEFT_FOOT_KICK = IMI_GESTURE_RIGHT_KNEE_LIFT + 1;
  public final static int IMI_GESTURE_RIGHT_FOOT_KICK = IMI_GESTURE_LEFT_FOOT_KICK + 1;
  public final static int IMI_GESTURE_BODY_MOVE_FORWARD = IMI_GESTURE_RIGHT_FOOT_KICK + 1;
  public final static int IMI_GESTURE_BODY_MOVE_BACKWARD = IMI_GESTURE_BODY_MOVE_FORWARD + 1;
  public final static int IMI_GESTURE_BODY_MOVE_LEFT = IMI_GESTURE_BODY_MOVE_BACKWARD + 1;
  public final static int IMI_GESTURE_BODY_MOVE_RIGHT = IMI_GESTURE_BODY_MOVE_LEFT + 1;
  public final static int IMI_GESTURE_TENNIS_SWIPE_LEFT = IMI_GESTURE_BODY_MOVE_RIGHT + 1;
  public final static int IMI_GESTURE_TENNIS_SWIPE_RIGHT = IMI_GESTURE_TENNIS_SWIPE_LEFT + 1;
  public final static int IMI_GESTURE_APPLAUSE = IMI_GESTURE_TENNIS_SWIPE_RIGHT + 1;
  public final static int IMI_GESTURE_BOWLING_THROW = IMI_GESTURE_APPLAUSE + 1;
  public final static int IMI_GESTURE_DEFENSE = IMI_GESTURE_BOWLING_THROW + 1;
  public final static int IMI_GESTURE_DRIVE = IMI_GESTURE_DEFENSE + 1;
  public final static int IMI_GESTURE_RIGHT_HAND_THROW_DART = IMI_GESTURE_DRIVE + 1;
  public final static int IMI_GESTURE_BASEBALL_HITTING = IMI_GESTURE_RIGHT_HAND_THROW_DART + 1;
  public final static int IMI_GESTURE_LEFT_FOOT_STOMP = IMI_GESTURE_BASEBALL_HITTING + 1;
  public final static int IMI_GESTURE_RIGHT_FOOT_STOMP = IMI_GESTURE_LEFT_FOOT_STOMP + 1;
  public final static int IMI_GESTURE_LEFT_FOOT_SIDE_KICK = IMI_GESTURE_RIGHT_FOOT_STOMP + 1;
  public final static int IMI_GESTURE_RIGHT_FOOT_SIDE_KICK = IMI_GESTURE_LEFT_FOOT_SIDE_KICK + 1;
  public final static int IMI_GESTURE_SHAKE_FISTS = IMI_GESTURE_RIGHT_FOOT_SIDE_KICK + 1;
  public final static int IMI_GESTURE_GAME_SQUAT = IMI_GESTURE_SHAKE_FISTS + 1;
  public final static int IMI_GESTURE_LEFT_ARM_135_DEGREE = IMI_GESTURE_GAME_SQUAT + 1;
  public final static int IMI_GESTURE_RIGHT_ARM_135_DEGREE = IMI_GESTURE_LEFT_ARM_135_DEGREE + 1;
  public final static int IMI_GESTURE_LEFT_ARM_135_TO_90_DEGREE = IMI_GESTURE_RIGHT_ARM_135_DEGREE + 1;
  public final static int IMI_GESTURE_RIGHT_ARM_135_TO_90_DEGREE = IMI_GESTURE_LEFT_ARM_135_TO_90_DEGREE + 1;
  public final static int IMI_GESTURE_LEFT_ARM_45_TO_90_DEGREE = IMI_GESTURE_RIGHT_ARM_135_TO_90_DEGREE + 1;
  public final static int IMI_GESTURE_RIGHT_ARM_45_TO_90_DEGREE = IMI_GESTURE_LEFT_ARM_45_TO_90_DEGREE + 1;
  public final static int IMI_GESTURE_COUNT = IMI_GESTURE_RIGHT_ARM_45_TO_90_DEGREE + 1;
}

