/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiHandSkeletonData extends ImiData {
  private transient long swigCPtr;

  public ImiHandSkeletonData(long cPtr, boolean cMemoryOwn) {
    super(mragent_data_javaJNI.ImiHandSkeletonData_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiHandSkeletonData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiHandSkeletonData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiHandSkeletonData(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setTrackingState(int value) {
    mragent_data_javaJNI.ImiHandSkeletonData_trackingState_set(swigCPtr, this, value);
  }

  public int getTrackingState() {
    return mragent_data_javaJNI.ImiHandSkeletonData_trackingState_get(swigCPtr, this);
  }

  public void setTrackingID(long value) {
    mragent_data_javaJNI.ImiHandSkeletonData_trackingID_set(swigCPtr, this, value);
  }

  public long getTrackingID() {
    return mragent_data_javaJNI.ImiHandSkeletonData_trackingID_get(swigCPtr, this);
  }

  public void setHandType(int value) {
    mragent_data_javaJNI.ImiHandSkeletonData_handType_set(swigCPtr, this, value);
  }

  public int getHandType() {
    return mragent_data_javaJNI.ImiHandSkeletonData_handType_get(swigCPtr, this);
  }

  public void setHandState(int value) {
    mragent_data_javaJNI.ImiHandSkeletonData_handState_set(swigCPtr, this, value);
  }

  public int getHandState() {
    return mragent_data_javaJNI.ImiHandSkeletonData_handState_get(swigCPtr, this);
  }

  public void setWristPosition(ImiVector4 value) {
    mragent_data_javaJNI.ImiHandSkeletonData_wristPosition_set(swigCPtr, this, ImiVector4.getCPtr(value), value);
  }

  public ImiVector4 getWristPosition() {
    long cPtr = mragent_data_javaJNI.ImiHandSkeletonData_wristPosition_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImiVector4(cPtr, false);
  }

  public void setSkeletonPositions(ImiVector4[] value) {
    mragent_data_javaJNI.ImiHandSkeletonData_skeletonPositions_set(swigCPtr, this, value);
  }

  public ImiVector4[] getSkeletonPositions() {
    return mragent_data_javaJNI.ImiHandSkeletonData_skeletonPositions_get(swigCPtr, this);
}

  public void setSkeletonOrientations(ImiSkeletonOrientationData[] value) {
    mragent_data_javaJNI.ImiHandSkeletonData_skeletonOrientations_set(swigCPtr, this, value);
  }

  public ImiSkeletonOrientationData[] getSkeletonOrientations() {
    return mragent_data_javaJNI.ImiHandSkeletonData_skeletonOrientations_get(swigCPtr, this);
}

  public void getVertexes(SWIGTYPE_p_float array_ref, int array_len) {
    mragent_data_javaJNI.ImiHandSkeletonData_getVertexes(swigCPtr, this, SWIGTYPE_p_float.getCPtr(array_ref), array_len);
  }

  public static int[] getSkeletonLinkIndexes() {
    return mragent_data_javaJNI.ImiHandSkeletonData_getSkeletonLinkIndexes();
}

  public String toString() {
    return mragent_data_javaJNI.ImiHandSkeletonData_toString(swigCPtr, this);
  }

  public ImiHandSkeletonData() {
    this(mragent_data_javaJNI.new_ImiHandSkeletonData(), true);
  }

  public final static class ImiHandType {
    public final static int IMI_HAND_LEFT = 0;
    public final static int IMI_HAND_RIGHT = 1;
  }

  public final static class ImiHandState {
    public final static int IMI_HAND_UNSURE = 0;
    public final static int IMI_HAND_GRASP = 1;
    public final static int IMI_HAND_OPEN = 2;
  }

  public final static class ImiHandSkeletonPositionIndex {
    public final static int IMI_HAND_SKELETON_WRIST = 0;
    public final static int IMI_HAND_SKELETON_TMCP = 1;
    public final static int IMI_HAND_SKELETON_IMCP = 2;
    public final static int IMI_HAND_SKELETON_MMCP = 3;
    public final static int IMI_HAND_SKELETON_RMCP = 4;
    public final static int IMI_HAND_SKELETON_PMCP = 5;
    public final static int IMI_HAND_SKELETON_TPIP = 6;
    public final static int IMI_HAND_SKELETON_TDIP = 7;
    public final static int IMI_HAND_SKELETON_TTIP = 8;
    public final static int IMI_HAND_SKELETON_IPIP = 9;
    public final static int IMI_HAND_SKELETON_IDIP = 10;
    public final static int IMI_HAND_SKELETON_ITIP = 11;
    public final static int IMI_HAND_SKELETON_MPIP = 12;
    public final static int IMI_HAND_SKELETON_MDIP = 13;
    public final static int IMI_HAND_SKELETON_MTIP = 14;
    public final static int IMI_HAND_SKELETON_RPIP = 15;
    public final static int IMI_HAND_SKELETON_RDIP = 16;
    public final static int IMI_HAND_SKELETON_RTIP = 17;
    public final static int IMI_HAND_SKELETON_PPIP = 18;
    public final static int IMI_HAND_SKELETON_PDIP = 19;
    public final static int IMI_HAND_SKELETON_PTIP = 20;
    public final static int IMI_HAND_SKELETON_COUNT = 21;
  }

}
