/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiMat4f {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImiMat4f(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiMat4f obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiMat4f obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiMat4f(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(float[] value) {
    mragent_data_javaJNI.ImiMat4f_data_set(swigCPtr, this, value);
  }

  public float[] getData() {
    return mragent_data_javaJNI.ImiMat4f_data_get(swigCPtr, this);
  }

  public String toString() {
    return mragent_data_javaJNI.ImiMat4f_toString(swigCPtr, this);
  }

  public ImiMat4f() {
    this(mragent_data_javaJNI.new_ImiMat4f(), true);
  }

}
