/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiMattingData extends ImiData {
  private transient long swigCPtr;

  public ImiMattingData(long cPtr, boolean cMemoryOwn) {
    super(mragent_data_javaJNI.ImiMattingData_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiMattingData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiMattingData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiMattingData(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setWidth(int value) {
    mragent_data_javaJNI.ImiMattingData_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return mragent_data_javaJNI.ImiMattingData_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    mragent_data_javaJNI.ImiMattingData_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return mragent_data_javaJNI.ImiMattingData_height_get(swigCPtr, this);
  }

  public String toString() {
    return mragent_data_javaJNI.ImiMattingData_toString(swigCPtr, this);
  }

  public boolean empty() {
    return mragent_data_javaJNI.ImiMattingData_empty(swigCPtr, this);
  }

  public ImiMattingData() {
    this(mragent_data_javaJNI.new_ImiMattingData(), true);
  }

}
