/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiPoint2D extends ImiData {
  private transient long swigCPtr;

  public ImiPoint2D(long cPtr, boolean cMemoryOwn) {
    super(mragent_data_javaJNI.ImiPoint2D_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiPoint2D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiPoint2D obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiPoint2D(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setX(int value) {
    mragent_data_javaJNI.ImiPoint2D_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return mragent_data_javaJNI.ImiPoint2D_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    mragent_data_javaJNI.ImiPoint2D_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return mragent_data_javaJNI.ImiPoint2D_y_get(swigCPtr, this);
  }

  public ImiPoint2D(int x, int y) {
    this(mragent_data_javaJNI.new_ImiPoint2D__SWIG_0(x, y), true);
  }

  public ImiPoint2D(int x) {
    this(mragent_data_javaJNI.new_ImiPoint2D__SWIG_1(x), true);
  }

  public ImiPoint2D() {
    this(mragent_data_javaJNI.new_ImiPoint2D__SWIG_2(), true);
  }

  public String toString() {
    return mragent_data_javaJNI.ImiPoint2D_toString(swigCPtr, this);
  }

}
