/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public final class ImiPixelFormat {
  public final static int IMI_PIXEL_FORMAT_IMAGE_DEP_16BIT = 0;
  public final static int IMI_PIXEL_FORMAT_IMAGE_YUV422 = 1;
  public final static int IMI_PIXEL_FORMAT_IMAGE_H264 = 2;
  public final static int IMI_PIXEL_FORMAT_IMAGE_RGB24 = 3;
  public final static int IMI_PIXEL_FORMAT_IMAGE_YUV420SP = 4;
  public final static int IMI_PIXEL_FORMAT_IMAGE_MJPEG = 5;
  public final static int IMI_PIXEL_FORMAT_IMAGE_YUYV = 6;
  public final static int IMI_PIXEL_FORMAT_INVALID = 16;
}

