/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiPositionTrackData extends ImiData {
  private transient long swigCPtr;

  public ImiPositionTrackData(long cPtr, boolean cMemoryOwn) {
    super(mragent_data_javaJNI.ImiPositionTrackData_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiPositionTrackData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiPositionTrackData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiPositionTrackData(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setSlamPose(ImiSlamPoseData value) {
    mragent_data_javaJNI.ImiPositionTrackData_slamPose_set(swigCPtr, this, ImiSlamPoseData.getCPtr(value), value);
  }

  public ImiSlamPoseData getSlamPose() {
    long cPtr = mragent_data_javaJNI.ImiPositionTrackData_slamPose_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImiSlamPoseData(cPtr, false);
  }

  public void setMoveTrackData(ImiMoveTrackData[] value) {
    mragent_data_javaJNI.ImiPositionTrackData_moveTrackData_set(swigCPtr, this, value);
  }

  public ImiMoveTrackData[] getMoveTrackData() {
    return mragent_data_javaJNI.ImiPositionTrackData_moveTrackData_get(swigCPtr, this);
}

  public void setAccData(ImiVector4 value) {
    mragent_data_javaJNI.ImiPositionTrackData_accData_set(swigCPtr, this, ImiVector4.getCPtr(value), value);
  }

  public ImiVector4 getAccData() {
    long cPtr = mragent_data_javaJNI.ImiPositionTrackData_accData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImiVector4(cPtr, false);
  }

  public String toString() {
    return mragent_data_javaJNI.ImiPositionTrackData_toString(swigCPtr, this);
  }

  public ImiPositionTrackData() {
    this(mragent_data_javaJNI.new_ImiPositionTrackData(), true);
  }

}
