/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiRect extends ImiData {
  private transient long swigCPtr;

  public ImiRect(long cPtr, boolean cMemoryOwn) {
    super(mragent_data_javaJNI.ImiRect_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiRect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiRect obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiRect(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setX(int value) {
    mragent_data_javaJNI.ImiRect_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return mragent_data_javaJNI.ImiRect_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    mragent_data_javaJNI.ImiRect_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return mragent_data_javaJNI.ImiRect_y_get(swigCPtr, this);
  }

  public void setWidth(int value) {
    mragent_data_javaJNI.ImiRect_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return mragent_data_javaJNI.ImiRect_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    mragent_data_javaJNI.ImiRect_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return mragent_data_javaJNI.ImiRect_height_get(swigCPtr, this);
  }

  public ImiRect(int x, int y, int w, int h) {
    this(mragent_data_javaJNI.new_ImiRect__SWIG_0(x, y, w, h), true);
  }

  public ImiRect(int x, int y, int w) {
    this(mragent_data_javaJNI.new_ImiRect__SWIG_1(x, y, w), true);
  }

  public ImiRect(int x, int y) {
    this(mragent_data_javaJNI.new_ImiRect__SWIG_2(x, y), true);
  }

  public ImiRect(int x) {
    this(mragent_data_javaJNI.new_ImiRect__SWIG_3(x), true);
  }

  public ImiRect() {
    this(mragent_data_javaJNI.new_ImiRect__SWIG_4(), true);
  }

  public String toString() {
    return mragent_data_javaJNI.ImiRect_toString(swigCPtr, this);
  }

}
