/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public final class ImiSkeletonTrackState {
  public final static int IMI_SKELETON_NOT_TRACKED = 0;
  public final static int IMI_SKELETON_POSITION_ONLY = 1;
  public final static int IMI_SKELETON_TRACKED = 2;
  public final static int IMI_SKELETON_TRACKING = 3;
  public final static int IMI_SKELETON_FAILED = 4;
}

