/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiSkeletonOrientationData extends ImiData {
  private transient long swigCPtr;

  public ImiSkeletonOrientationData(long cPtr, boolean cMemoryOwn) {
    super(mragent_data_javaJNI.ImiSkeletonOrientationData_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiSkeletonOrientationData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiSkeletonOrientationData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiSkeletonOrientationData(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setHierarchicalRotation(ImiMat3f value) {
    mragent_data_javaJNI.ImiSkeletonOrientationData_hierarchicalRotation_set(swigCPtr, this, ImiMat3f.getCPtr(value), value);
  }

  public ImiMat3f getHierarchicalRotation() {
    long cPtr = mragent_data_javaJNI.ImiSkeletonOrientationData_hierarchicalRotation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImiMat3f(cPtr, false);
  }

  public void setAbsoluteRotation(ImiMat3f value) {
    mragent_data_javaJNI.ImiSkeletonOrientationData_absoluteRotation_set(swigCPtr, this, ImiMat3f.getCPtr(value), value);
  }

  public ImiMat3f getAbsoluteRotation() {
    long cPtr = mragent_data_javaJNI.ImiSkeletonOrientationData_absoluteRotation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImiMat3f(cPtr, false);
  }

  public void setEulerAngles(ImiVector4 value) {
    mragent_data_javaJNI.ImiSkeletonOrientationData_eulerAngles_set(swigCPtr, this, ImiVector4.getCPtr(value), value);
  }

  public ImiVector4 getEulerAngles() {
    long cPtr = mragent_data_javaJNI.ImiSkeletonOrientationData_eulerAngles_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImiVector4(cPtr, false);
  }

  public String toString() {
    return mragent_data_javaJNI.ImiSkeletonOrientationData_toString(swigCPtr, this);
  }

  public ImiSkeletonOrientationData() {
    this(mragent_data_javaJNI.new_ImiSkeletonOrientationData(), true);
  }

}
