/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiSlamPoseData extends ImiData {
  private transient long swigCPtr;

  public ImiSlamPoseData(long cPtr, boolean cMemoryOwn) {
    super(mragent_data_javaJNI.ImiSlamPoseData_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiSlamPoseData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiSlamPoseData obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiSlamPoseData(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setTrackState(int value) {
    mragent_data_javaJNI.ImiSlamPoseData_trackState_set(swigCPtr, this, value);
  }

  public int getTrackState() {
    return mragent_data_javaJNI.ImiSlamPoseData_trackState_get(swigCPtr, this);
  }

  public void setCameraPose(ImiMat4f value) {
    mragent_data_javaJNI.ImiSlamPoseData_cameraPose_set(swigCPtr, this, ImiMat4f.getCPtr(value), value);
  }

  public ImiMat4f getCameraPose() {
    long cPtr = mragent_data_javaJNI.ImiSlamPoseData_cameraPose_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImiMat4f(cPtr, false);
  }

  public String toString() {
    return mragent_data_javaJNI.ImiSlamPoseData_toString(swigCPtr, this);
  }

  public ImiSlamPoseData() {
    this(mragent_data_javaJNI.new_ImiSlamPoseData(), true);
  }

  public final static class SlamPoseTrackingState {
    public final static int CAMERA_POSE = 0;
    public final static int RESET_POSE = 1;
    public final static int INVALID_POSE = 2;
  }

}
