/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public final class ImiSensorType {
  public final static int COLOR = 1;
  public final static int DEPTH = (0x01 << 1);
  public final static int IR = (0x01 << 2);
  public final static int USERTRACK = (0x01 << 3);
  public final static int FACEDETECT = (0x01 << 4);
  public final static int POSITIONTRACK = (0x01 << 5);
  public final static int MOVETRACK = (0x01 << 6);
  public final static int AUDIO = (0x01 << 7);
  public final static int ACTION = (0x01 << 8);
}

