/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiVector4I extends ImiData {
  private transient long swigCPtr;

  public ImiVector4I(long cPtr, boolean cMemoryOwn) {
    super(mragent_data_javaJNI.ImiVector4I_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiVector4I obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiVector4I obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiVector4I(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setX(int value) {
    mragent_data_javaJNI.ImiVector4I_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return mragent_data_javaJNI.ImiVector4I_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    mragent_data_javaJNI.ImiVector4I_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return mragent_data_javaJNI.ImiVector4I_y_get(swigCPtr, this);
  }

  public void setZ(int value) {
    mragent_data_javaJNI.ImiVector4I_z_set(swigCPtr, this, value);
  }

  public int getZ() {
    return mragent_data_javaJNI.ImiVector4I_z_get(swigCPtr, this);
  }

  public void setW(int value) {
    mragent_data_javaJNI.ImiVector4I_w_set(swigCPtr, this, value);
  }

  public int getW() {
    return mragent_data_javaJNI.ImiVector4I_w_get(swigCPtr, this);
  }

  public ImiVector4I() {
    this(mragent_data_javaJNI.new_ImiVector4I__SWIG_0(), true);
  }

  public ImiVector4I(int x, int y, int z, int w) {
    this(mragent_data_javaJNI.new_ImiVector4I__SWIG_1(x, y, z, w), true);
  }

  public ImiVector4I(int x, int y, int z) {
    this(mragent_data_javaJNI.new_ImiVector4I__SWIG_2(x, y, z), true);
  }

  public String toString() {
    return mragent_data_javaJNI.ImiVector4I_toString(swigCPtr, this);
  }

}
