/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class ImiVector4 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ImiVector4(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ImiVector4 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ImiVector4 obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_ImiVector4(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    mragent_data_javaJNI.ImiVector4_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return mragent_data_javaJNI.ImiVector4_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    mragent_data_javaJNI.ImiVector4_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return mragent_data_javaJNI.ImiVector4_y_get(swigCPtr, this);
  }

  public void setZ(float value) {
    mragent_data_javaJNI.ImiVector4_z_set(swigCPtr, this, value);
  }

  public float getZ() {
    return mragent_data_javaJNI.ImiVector4_z_get(swigCPtr, this);
  }

  public void setW(float value) {
    mragent_data_javaJNI.ImiVector4_w_set(swigCPtr, this, value);
  }

  public float getW() {
    return mragent_data_javaJNI.ImiVector4_w_get(swigCPtr, this);
  }

  public String toString() {
    return mragent_data_javaJNI.ImiVector4_toString(swigCPtr, this);
  }

  public ImiVector4() {
    this(mragent_data_javaJNI.new_ImiVector4(), true);
  }

}
