/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class LogConfig extends ImiData {
  private transient long swigCPtr;

  public LogConfig(long cPtr, boolean cMemoryOwn) {
    super(mragent_data_javaJNI.LogConfig_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(LogConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(LogConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mragent_data_javaJNI.delete_LogConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setPOutputDir(String value) {
    mragent_data_javaJNI.LogConfig_pOutputDir_set(swigCPtr, this, value);
  }

  public String getPOutputDir() {
    return mragent_data_javaJNI.LogConfig_pOutputDir_get(swigCPtr, this);
  }

  public void setLevel(long value) {
    mragent_data_javaJNI.LogConfig_level_set(swigCPtr, this, value);
  }

  public long getLevel() {
    return mragent_data_javaJNI.LogConfig_level_get(swigCPtr, this);
  }

  public void setBConsole(boolean value) {
    mragent_data_javaJNI.LogConfig_bConsole_set(swigCPtr, this, value);
  }

  public boolean getBConsole() {
    return mragent_data_javaJNI.LogConfig_bConsole_get(swigCPtr, this);
  }

  public void setBFile(boolean value) {
    mragent_data_javaJNI.LogConfig_bFile_set(swigCPtr, this, value);
  }

  public boolean getBFile() {
    return mragent_data_javaJNI.LogConfig_bFile_get(swigCPtr, this);
  }

  public LogConfig() {
    this(mragent_data_javaJNI.new_LogConfig(), true);
  }

}
