/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public final class MrAgentException {
  public final static int IMI_MRMANAGER_RESUME = 0;
  public final static int IMI_MRMANAGER_TIMEOUT = IMI_MRMANAGER_RESUME + 1;
  public final static int IMI_MRMANAGER_EXIT = IMI_MRMANAGER_TIMEOUT + 1;
}

