/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public class mragent_javaJNI {

    //java code
    static {
        System.loadLibrary("mragent_jni");
    }


  public final static native String getVersion();
  public final static native void delete_AppContext(long jarg1);
  public final static native long new_AppContext();
  public final static native void AppContext_director_connect(AppContext obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void AppContext_change_ownership(AppContext obj, long cptr, boolean take_or_release);
  public final static native long new_ImiContext(long jarg1, AppContext jarg1_);
  public final static native void delete_ImiContext(long jarg1);
  public final static native long ImiContext_create(long jarg1, AppContext jarg1_);
  public final static native long ImiContext_getContext();
  public final static native boolean ImiContext_initialize(long jarg1, ImiContext jarg1_, String jarg2);
  public final static native void ImiContext_setRemoteAddress(long jarg1, ImiContext jarg1_, String jarg2);
  public final static native void ImiContext_release(long jarg1, ImiContext jarg1_);
  public final static native long ImiContext_createDevice(long jarg1, ImiContext jarg1_);
  public final static native int ImiContext_getLastError(long jarg1, ImiContext jarg1_);
  public final static native String ImiContext_GetErrorString(int jarg1);
  public final static native int ImiContext_setLogConfig(long jarg1, ImiContext jarg1_, long jarg2, LogConfig jarg2_);
  public final static native void delete_IImiDeviceProperty(long jarg1);
  public final static native int IImiDeviceProperty_dataSize(long jarg1, IImiDeviceProperty jarg1_);
  public final static native long new_MrAgentExceptionHandler();
  public final static native void delete_MrAgentExceptionHandler(long jarg1);
  public final static native void MrAgentExceptionHandler_onExceptionHandle(long jarg1, MrAgentExceptionHandler jarg1_, int jarg2);
  public final static native void MrAgentExceptionHandler_onExceptionHandleSwigExplicitMrAgentExceptionHandler(long jarg1, MrAgentExceptionHandler jarg1_, int jarg2);
  public final static native void MrAgentExceptionHandler_director_connect(MrAgentExceptionHandler obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void MrAgentExceptionHandler_change_ownership(MrAgentExceptionHandler obj, long cptr, boolean take_or_release);
  public final static native boolean IImiBaseDevice_sendCommand(long jarg1, IImiBaseDevice jarg1_, long jarg2);
  public final static native void IImiBaseDevice_setOnExceptionHandler(long jarg1, IImiBaseDevice jarg1_, long jarg2, MrAgentExceptionHandler jarg2_);
  public final static native int IImiBaseDevice_getMrManagerStatus(long jarg1, IImiBaseDevice jarg1_);
  public final static native void delete_IImiBaseDevice(long jarg1);
  public final static native long IImiBaseDevice_getSensor(long jarg1, IImiBaseDevice jarg1_, int jarg2);
  public final static native int IImiBaseDevice_open(long jarg1, IImiBaseDevice jarg1_, int jarg2);
  public final static native int IImiBaseDevice_close(long jarg1, IImiBaseDevice jarg1_);
  public final static native long IImiBaseDevice_getVersions(long jarg1, IImiBaseDevice jarg1_);
  public final static native int IImiBaseDevice_setProperty(long jarg1, IImiBaseDevice jarg1_, int jarg2, long jarg3, IImiDeviceProperty jarg3_);
  public final static native int IImiBaseDevice_getProperty(long jarg1, IImiBaseDevice jarg1_, int jarg2, long jarg3, IImiDeviceProperty jarg3_);
  public final static native void delete_IImiBaseSensor(long jarg1);
  public final static native int IImiBaseSensor_getSensorType(long jarg1, IImiBaseSensor jarg1_);
  public final static native int IImiBaseSensor_start__SWIG_0(long jarg1, IImiBaseSensor jarg1_, int jarg2);
  public final static native int IImiBaseSensor_start__SWIG_1(long jarg1, IImiBaseSensor jarg1_);
  public final static native int IImiBaseSensor_stop(long jarg1, IImiBaseSensor jarg1_);
  public final static native int IImiBaseSensor_release(long jarg1, IImiBaseSensor jarg1_);
  public final static native boolean IImiBaseSensor_isStarted(long jarg1, IImiBaseSensor jarg1_);
  public final static native long IImiBaseSensor_readFrame__SWIG_0(long jarg1, IImiBaseSensor jarg1_, int jarg2);
  public final static native long IImiBaseSensor_readFrame__SWIG_1(long jarg1, IImiBaseSensor jarg1_);
  public final static native int IImiBaseSensor_getWidth(long jarg1, IImiBaseSensor jarg1_);
  public final static native int IImiBaseSensor_getHeight(long jarg1, IImiBaseSensor jarg1_);
  public final static native int IImiBaseSensor_getDepth(long jarg1, IImiBaseSensor jarg1_);
  public final static native void IImiBaseSensor_setWidth(long jarg1, IImiBaseSensor jarg1_, int jarg2);
  public final static native void IImiBaseSensor_setHeight(long jarg1, IImiBaseSensor jarg1_, int jarg2);
  public final static native void IImiBaseSensor_setDepth(long jarg1, IImiBaseSensor jarg1_, int jarg2);
  public final static native void delete_IImiBaseFrame(long jarg1);
  public final static native int IImiBaseFrame_getSensorType(long jarg1, IImiBaseFrame jarg1_);
  public final static native int IImiBaseFrame_getFrameNum(long jarg1, IImiBaseFrame jarg1_);
  public final static native int IImiBaseFrame_getTimeStamp(long jarg1, IImiBaseFrame jarg1_);
  public final static native int IImiBaseFrame_getWidth(long jarg1, IImiBaseFrame jarg1_);
  public final static native int IImiBaseFrame_getHeight(long jarg1, IImiBaseFrame jarg1_);
  public final static native int IImiBaseFrame_getDepth(long jarg1, IImiBaseFrame jarg1_);
  public final static native void delete_IImiImageFrame(long jarg1);
  public final static native int IImiImageFrame_getPixelFormat(long jarg1, IImiImageFrame jarg1_);
  public final static native int IImiImageFrame_getFps(long jarg1, IImiImageFrame jarg1_);
  public final static native void IImiImageFrame_getData(long jarg1, IImiImageFrame jarg1_, boolean _arg2, java.lang.Object jarg2);
  public final static native int IImiImageFrame_getDataSize(long jarg1, IImiImageFrame jarg1_);
  public final static native String IImiImageFrame_toString(long jarg1, IImiImageFrame jarg1_);
  public final static native long new_IImiColorFrame(int jarg1);
  public final static native void delete_IImiColorFrame(long jarg1);
  public final static native long IImiColorFrame_asMe(long jarg1, IImiBaseFrame jarg1_);
  public final static native void IImiColorFrame_getData(long jarg1, IImiColorFrame jarg1_, boolean _arg2, java.lang.Object jarg2);
  public final static native int IImiColorFrame_getDataSize(long jarg1, IImiColorFrame jarg1_);
  public final static native void IImiColorFrame_release(long jarg1, IImiColorFrame jarg1_);
  public final static native long new_IImiColorSensor(long jarg1, IImiBaseDevice jarg1_);
  public final static native void delete_IImiColorSensor(long jarg1);
  public final static native long IImiColorSensor_asMe(long jarg1, IImiBaseSensor jarg1_);
  public final static native int IImiColorSensor_start__SWIG_0(long jarg1, IImiColorSensor jarg1_, int jarg2);
  public final static native int IImiColorSensor_start__SWIG_1(long jarg1, IImiColorSensor jarg1_);
  public final static native int IImiColorSensor_stop(long jarg1, IImiColorSensor jarg1_);
  public final static native long IImiColorSensor_readFrame__SWIG_0(long jarg1, IImiColorSensor jarg1_, int jarg2);
  public final static native long IImiColorSensor_readFrame__SWIG_1(long jarg1, IImiColorSensor jarg1_);
  public final static native long new_IImiDepthSensor(long jarg1, IImiBaseDevice jarg1_);
  public final static native void delete_IImiDepthSensor(long jarg1);
  public final static native long IImiDepthSensor_asMe(long jarg1, IImiBaseSensor jarg1_);
  public final static native String IImiDepthSensor_toString(long jarg1, IImiDepthSensor jarg1_);
  public final static native long new_IImiDepthFrame();
  public final static native void delete_IImiDepthFrame(long jarg1);
  public final static native long IImiDepthFrame_asMe(long jarg1, IImiBaseFrame jarg1_);
  public final static native void IImiDepthFrame_getRgbData(long jarg1, IImiDepthFrame jarg1_, boolean _arg2, java.lang.Object jarg2);
  public final static native long new_IImiIRSensor(long jarg1, IImiBaseDevice jarg1_);
  public final static native void delete_IImiIRSensor(long jarg1);
  public final static native long IImiIRSensor_asMe(long jarg1, IImiBaseSensor jarg1_);
  public final static native void delete_IImiIRFrame(long jarg1);
  public final static native long IImiIRFrame_asMe(long jarg1, IImiBaseFrame jarg1_);
  public final static native void IImiIRFrame_getRgbData(long jarg1, IImiIRFrame jarg1_, boolean _arg2, java.lang.Object jarg2);
  public final static native long new_IImiUserTrackSensor(long jarg1, IImiBaseDevice jarg1_);
  public final static native void delete_IImiUserTrackSensor(long jarg1);
  public final static native long IImiUserTrackSensor_asMe(long jarg1, IImiBaseSensor jarg1_);
  public final static native int IImiUserTrackSensor_start__SWIG_0(long jarg1, IImiUserTrackSensor jarg1_, int jarg2);
  public final static native int IImiUserTrackSensor_start__SWIG_1(long jarg1, IImiUserTrackSensor jarg1_);
  public final static native int IImiUserTrackSensor_stop(long jarg1, IImiUserTrackSensor jarg1_);
  public final static native long IImiUserTrackSensor_readFrame__SWIG_0(long jarg1, IImiUserTrackSensor jarg1_, int jarg2);
  public final static native long IImiUserTrackSensor_readFrame__SWIG_1(long jarg1, IImiUserTrackSensor jarg1_);
  public final static native long new_IImiUserTrackFrame(int jarg1);
  public final static native void delete_IImiUserTrackFrame(long jarg1);
  public final static native void IImiUserTrackFrame_release(long jarg1, IImiUserTrackFrame jarg1_);
  public final static native long IImiUserTrackFrame_asMe(long jarg1, IImiBaseFrame jarg1_);
  public final static native long IImiUserTrackFrame_getBodySkeleton__SWIG_0(long jarg1, IImiUserTrackFrame jarg1_);
  public final static native boolean IImiUserTrackFrame_getBodySkeleton__SWIG_1(long jarg1, IImiUserTrackFrame jarg1_, long jarg2, ImiBodySkeleton jarg2_);
  public final static native long IImiUserTrackFrame_getHandSkeleton(long jarg1, IImiUserTrackFrame jarg1_);
  public final static native long IImiUserTrackFrame_getForegroundInfo(long jarg1, IImiUserTrackFrame jarg1_);
  public final static native int IImiUserTrackFrame_getForegroundData(long jarg1, IImiUserTrackFrame jarg1_, boolean _arg2, java.lang.Object jarg2);
  public final static native long IImiUserTrackFrame_getMattingInfo(long jarg1, IImiUserTrackFrame jarg1_);
  public final static native void IImiUserTrackFrame_getMattingData(long jarg1, IImiUserTrackFrame jarg1_, boolean _arg2, java.lang.Object jarg2);
  public final static native long IImiUserTrackFrame_getFaceFeatureFrame(long jarg1, IImiUserTrackFrame jarg1_);
  public final static native int IImiUserTrackFrame_getForegroundRgbData(long jarg1, IImiUserTrackFrame jarg1_, boolean _arg2, java.lang.Object jarg2, int jarg4);
  public final static native int IImiUserTrackFrame_getForegroundArgbData(long jarg1, IImiUserTrackFrame jarg1_, boolean _arg2, java.lang.Object jarg2, int jarg4);
  public final static native int IImiUserTrackFrame_getBodySkeletonData(long jarg1, IImiUserTrackFrame jarg1_, boolean _arg2, java.lang.Object jarg2);
  public final static native long new_IImiActionSensor(long jarg1, IImiBaseDevice jarg1_);
  public final static native void delete_IImiActionSensor(long jarg1);
  public final static native long IImiActionSensor_asMe(long jarg1, IImiBaseSensor jarg1_);
  public final static native void IImiActionSensor_onRunActionsData(long jarg1, IImiActionSensor jarg1_);
  public final static native int IImiActionSensor_start__SWIG_0(long jarg1, IImiActionSensor jarg1_, int jarg2);
  public final static native int IImiActionSensor_start__SWIG_1(long jarg1, IImiActionSensor jarg1_);
  public final static native int IImiActionSensor_stop(long jarg1, IImiActionSensor jarg1_);
  public final static native boolean IImiActionSensor_isStarted(long jarg1, IImiActionSensor jarg1_);
  public final static native long IImiActionSensor_readFrame__SWIG_0(long jarg1, IImiActionSensor jarg1_, int jarg2);
  public final static native long IImiActionSensor_readFrame__SWIG_1(long jarg1, IImiActionSensor jarg1_);
  public final static native long new_IImiActionFrame();
  public final static native void delete_IImiActionFrame(long jarg1);
  public final static native long IImiActionFrame_asMe(long jarg1, IImiBaseFrame jarg1_);
  public final static native long IImiActionFrame_getAccompanyFrame(long jarg1, IImiActionFrame jarg1_);
  public final static native String IImiActionFrame_getActionsData(long jarg1, IImiActionFrame jarg1_);
  public final static native long DataUtil_createImiBodySkeleton();
  public final static native long new_DataUtil();
  public final static native void delete_DataUtil(long jarg1);
  public final static native long new_IInt32Property__SWIG_0();
  public final static native long new_IInt32Property__SWIG_1(int jarg1);
  public final static native void delete_IInt32Property(long jarg1);
  public final static native void IInt32Property_set(long jarg1, IInt32Property jarg1_, int jarg2);
  public final static native int IInt32Property_get(long jarg1, IInt32Property jarg1_);
  public final static native int IInt32Property_dataSize(long jarg1, IInt32Property jarg1_);
  public final static native long new_IInt16Property__SWIG_0();
  public final static native long new_IInt16Property__SWIG_1(short jarg1);
  public final static native void delete_IInt16Property(long jarg1);
  public final static native void IInt16Property_set(long jarg1, IInt16Property jarg1_, short jarg2);
  public final static native short IInt16Property_get(long jarg1, IInt16Property jarg1_);
  public final static native int IInt16Property_dataSize(long jarg1, IInt16Property jarg1_);
  public final static native long new_IInt64Property__SWIG_0();
  public final static native long new_IInt64Property__SWIG_1(int jarg1);
  public final static native void delete_IInt64Property(long jarg1);
  public final static native void IInt64Property_set(long jarg1, IInt64Property jarg1_, int jarg2);
  public final static native int IInt64Property_get(long jarg1, IInt64Property jarg1_);
  public final static native int IInt64Property_dataSize(long jarg1, IInt64Property jarg1_);
  public final static native long new_IFloatProperty__SWIG_0();
  public final static native long new_IFloatProperty__SWIG_1(float jarg1);
  public final static native void delete_IFloatProperty(long jarg1);
  public final static native void IFloatProperty_set(long jarg1, IFloatProperty jarg1_, float jarg2);
  public final static native float IFloatProperty_get(long jarg1, IFloatProperty jarg1_);
  public final static native int IFloatProperty_dataSize(long jarg1, IFloatProperty jarg1_);
  public final static native long new_IInt8Property__SWIG_0();
  public final static native long new_IInt8Property__SWIG_1(short jarg1);
  public final static native void delete_IInt8Property(long jarg1);
  public final static native void IInt8Property_set(long jarg1, IInt8Property jarg1_, short jarg2);
  public final static native short IInt8Property_get(long jarg1, IInt8Property jarg1_);
  public final static native int IInt8Property_dataSize(long jarg1, IInt8Property jarg1_);
  public final static native long new_IImiCameraIntrinsicProperty__SWIG_0();
  public final static native long new_IImiCameraIntrinsicProperty__SWIG_1(long jarg1, ImiCameraIntrinsic jarg1_);
  public final static native void delete_IImiCameraIntrinsicProperty(long jarg1);
  public final static native void IImiCameraIntrinsicProperty_set(long jarg1, IImiCameraIntrinsicProperty jarg1_, long jarg2, ImiCameraIntrinsic jarg2_);
  public final static native long IImiCameraIntrinsicProperty_get(long jarg1, IImiCameraIntrinsicProperty jarg1_);
  public final static native int IImiCameraIntrinsicProperty_dataSize(long jarg1, IImiCameraIntrinsicProperty jarg1_);
  public final static native long IImiImageFrame_SWIGSmartPtrUpcast(long jarg1);
  public final static native long IImiColorFrame_SWIGSmartPtrUpcast(long jarg1);
  public final static native long IImiColorSensor_SWIGSmartPtrUpcast(long jarg1);
  public final static native long IImiDepthSensor_SWIGSmartPtrUpcast(long jarg1);
  public final static native long IImiDepthFrame_SWIGSmartPtrUpcast(long jarg1);
  public final static native long IImiIRSensor_SWIGSmartPtrUpcast(long jarg1);
  public final static native long IImiIRFrame_SWIGSmartPtrUpcast(long jarg1);
  public final static native long IImiUserTrackSensor_SWIGSmartPtrUpcast(long jarg1);
  public final static native long IImiUserTrackFrame_SWIGSmartPtrUpcast(long jarg1);
  public final static native long IImiActionSensor_SWIGSmartPtrUpcast(long jarg1);
  public final static native long IImiActionFrame_SWIGSmartPtrUpcast(long jarg1);
  public final static native long IInt32Property_SWIGUpcast(long jarg1);
  public final static native long IInt16Property_SWIGUpcast(long jarg1);
  public final static native long IInt64Property_SWIGUpcast(long jarg1);
  public final static native long IFloatProperty_SWIGUpcast(long jarg1);
  public final static native long IInt8Property_SWIGUpcast(long jarg1);
  public final static native long IImiCameraIntrinsicProperty_SWIGUpcast(long jarg1);

  public static void SwigDirector_MrAgentExceptionHandler_onExceptionHandle(MrAgentExceptionHandler jself, int exception) {
    jself.onExceptionHandle(exception);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
