/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sximi.mragent;

public final class MrManagerStatus {
  public final static int NORMAL = 0;
  public final static int EXIT = NORMAL + 1;
  public final static int UNKNOWN = EXIT + 1;
}

