/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_mragent_java_WRAP_H_
#define SWIG_mragent_java_WRAP_H_

class SwigDirector_AppContext : public imimr::AppContext, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_AppContext(JNIEnv *jenv);
    virtual ~SwigDirector_AppContext();
public:
    bool swig_overrides(int n) {
      return false;
    }
};

class SwigDirector_MrAgentExceptionHandler : public imimr::MrAgentExceptionHandler, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_MrAgentExceptionHandler(JNIEnv *jenv);
    virtual ~SwigDirector_MrAgentExceptionHandler();
    virtual void onExceptionHandle(imimr::MrAgentException exception);
public:
    bool swig_overrides(int n) {
      return (n < 1 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<1> swig_override;
};


#endif
