#ifndef _IMI_MRAGENT_VERSION_H_
#define _IMI_MRAGENT_VERSION_H_

#define IMI_MRAGENT_MAJOR_VERSION 1
#define IMI_MRAGENT_MINOR_VERSION 6
#define IMI_MRAGNET_REVISION_VERSION 2
#define IMI_MRAGNET_PATCH_VERSION 0

#endif //_IMI_MRAGENT_VERSION_H_
